objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>AddressBook (contact record) number used as a customer identifier and mastered in WinField ERP (JDE). This number makes sense only in the WinField universe.</description>
        <externalId>true</externalId>
        <inlineHelpText>AddressBook number from WinField ERP (JDE)</inlineHelpText>
        <label>Customer Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>Composite key that represents a globally unique customer ID. The key is built based on a concatenation of several items.
WinField and Purina: BU designation + AIMS Number
Dairy: Farm ID
Corporate:</description>
        <externalId>true</externalId>
        <label>Globally Unique Customer ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>winfield</fullName>
        <active>true</active>
        <label>WinField</label>
    </recordTypes>
</CustomObject>

objects/CalloutSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Customer_Key__c</fullName>
        <label>Customer Key</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Secret_Key__c</fullName>
        <label>Customer Secret Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Instance__c</fullName>
        <label>Salesforce Instance</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CalloutSettings</label>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Ag_Tech_Agreement__c</fullName>
        <formula>Related_External_User__r.Ag_Tech_Agreement__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ag Tech Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_External_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Customer User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <externalId>true</externalId>
        <label>BusinessLink ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Related_External_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related External User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <externalId>true</externalId>
        <label>BusinessLink ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ag_Tech_Agreement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ag Tech Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobClassification__c</fullName>
        <label>Job Function</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ag Member</fullName>
                </value>
                <value>
                    <fullName>Broker - Foodservice</fullName>
                </value>
                <value>
                    <fullName>Broker - Retail</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Member</fullName>
                </value>
                <value>
                    <fullName>Dairy Member Owner</fullName>
                </value>
                <value>
                    <fullName>Direct Ag Producer</fullName>
                </value>
                <value>
                    <fullName>Farmer</fullName>
                </value>
                <value>
                    <fullName>Member of a Member</fullName>
                </value>
                <value>
                    <fullName>Member Owner</fullName>
                </value>
                <value>
                    <fullName>Momentum Consultant</fullName>
                </value>
                <value>
                    <fullName>Nutritionist</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Retailer Management</fullName>
                </value>
                <value>
                    <fullName>Retailer Operations</fullName>
                </value>
                <value>
                    <fullName>Retailer Sales</fullName>
                </value>
                <value>
                    <fullName>RTech Partner</fullName>
                </value>
                <value>
                    <fullName>Warehousing Partner</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SendCasesToCRMCtrlTest.cls
@isTest
public class SendCasesToCRMCtrlTest{
    @testSetup static void setup() {
        RecordType accRT = [select id from RecordType where SobjectType = 'Account' LIMIT 1];
        RecordType caseRT = [select id from RecordType where SobjectType = 'Case' AND Name = 'New Customer Registration' LIMIT 1];
        
        CalloutSettings__c callout = new CalloutSettings__c();
        callout.Name = 'Focus';
        callout.Salesforce_Instance__c = 'https://focus--RGDev.cs43.my.salesforce.com';
        callout.Customer_Key__c = '3MVG9GnaLrwG9TQQUTjvaYOEKdnK0njgXFIMq8DXtPwZYG.VONq5efDUReFWR0vNpSZ.0zSdST_dhuhsgEyup';
        callout.Customer_Secret_Key__c = '6582018088481538566';
        callout.Username__c = 'dhruv.singh%40sf.winfield.rgdev';
        callout.Password__c = 'winfieldzif5yrqfhpiBwkYNpJFvKMzuk';
        insert callout;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='EMS External User' LIMIT 1];
        User u = [Select id from User where ProfileId =: p.Id AND JobClassification__c = 'Farmer' LIMIT 1];
                
        Account acc = new Account();
        acc.Name = 'test account';
        acc.GUID__c = 'testaccount';
        acc.RecordTypeId = accRT.Id;
        insert acc;
        
        Contact con = new Contact();
        con.FirstName = 'test';
        con.LastName = 'contact';
        con.AccountId = acc.Id;
        con.Related_External_User__c = u.Id;       
        insert con;      
        
        List<case> lCases = new List<case>{new case(RecordTypeId = caseRT.Id, ContactId = con.Id, Related_External_User__c = u.Id, Status = 'New', Subject = 'New Case for Test Class 1'),
            new case(RecordTypeId = caseRT.Id, ContactId = con.Id, Related_External_User__c = u.Id, Status = 'New', Subject = 'New Case for Test Class 2')};
        insert lCases;
    }
    
    @isTest static void testSyncCasesToCRM() {
        List<case> listOfcases = [select id, Contact.Account.Name, Contact.Account.Customer_Number__c, Contact.Account.BillingCity, 
            Contact.Account.BillingState, Related_External_User__r.Name, Related_External_User__r.Phone, 
            Related_External_User__r.Email, Related_External_User__r.Ag2Ag_ID__c, Contact.Name, Status, Origin, CaseNumber, Description, 
            Priority, Ag_Tech_Agreement__c from case where subject like 'New Case for Test Class%'];
                
        for(case c : listOfcases){
            c.status = 'Reviewed and Accepted';
        }
        
        update listOfcases;  
        
        Contact con = [select id, Ag2Ag_ID__c from contact where name like 'test%' limit 1];
        con.Ag2Ag_ID__c = 'test012';
        
        update con;               
        
        String jsonStr = '{{'+
                '"access_token":"00D630000008o4i!AQkAQBFgR_I5lF58UW6lC.UoYiP0nRsA2RVto5kTwG._pTokDFrklemAlyIgRR3mKoqm9P2ciNav1QJqZcLcwaWrXsfTDjzI",'+
                '"instance_url":"https://focus--RGDev.cs43.my.salesforce.com",'+
                '"id":"https://test.salesforce.com/id/00D630000008o4iEAA/00563000000T1f9AAC",'+
                '"token_type":"Bearer",'+
                '"issued_at":"1469511541846",'+
                '"signature":"467OwTpGWn9ZnYKhmswA8LeOqHV/q6QfpJO9CeF40LU="'+
                '}}';
        
        SendCasesToCRMCtrl.oauth = jsonStr;
        String result = SendCasesToCRMCtrl.sendCasesList(listOfcases);
        System.assertEquals('Success', result);
    }
}