objects/Account.object
<CustomObject>
    <fields>
        <fullName>AIMS_Number__c</fullName>
        <description>AIMS Number is a unique customer identifier mastered in Purina ERP (JDE). Globally unique across WinField and Purina.</description>
        <externalId>true</externalId>
        <inlineHelpText>AIMS Number from Purina ERP (JDE)</inlineHelpText>
        <label>AIMS Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit_Key__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WF</fullName>
                </value>
                <value>
                    <fullName>FEED</fullName>
                </value>
                <value>
                    <fullName>DAIRY</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>AddressBook (contact record) number used as a customer identifier and mastered in WinField ERP (JDE). This number makes sense only in the WinField universe.</description>
        <externalId>true</externalId>
        <inlineHelpText>AddressBook number from WinField ERP (JDE)</inlineHelpText>
        <label>Customer Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>Composite key that represents a globally unique customer ID. The key is built based on a concatenation of several items.
WinField and Purina: BU designation + AIMS Number
Dairy: Farm ID
Corporate:</description>
        <externalId>true</externalId>
        <label>Globally Unique Customer ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PAES_Number__c</fullName>
        <label>PAES Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/UserAccountService.cls
@RestResource(urlMapping='/ems/v1/acct/*/info')
global with sharing class UserAccountService {

    @HttpGet
    global static ResponseContainer doGet() {
   		RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
 	String acctId = req.requestURI.substring(req.requestURI.indexOf('/acct')+5).substringBetween('/');  
   
        if (acctId == null || acctId == '' || EncodingUtil.urlDecode(acctId,'UTF-8').trim().length() < 1) {
            return new ResponseContainer('Account GUID not found in the request',400);
        }
        
        List<Account> accts = [SELECT Id FROM Account WHERE GUID__c  = :acctId];
        if (accts.size() < 1)
         return new ResponseContainer('No such account: ' + acctId,404);
        else if (accts.size() > 1)
         return new ResponseContainer('More than one account found: ' + acctId,404);
        try{
            Account acct = [SELECT AccountNumber,Active__c,AIMS_Number__c,AnnualRevenue,
            BillingAddress,BillingCity,BillingCountry,BillingPostalCode,BillingState,BillingStreet,
            Business_Unit_Key__c,Customer_Number__c,GUID__c,Id,PAES_Number__c 
            FROM Account 
            ORDER BY Name LIMIT 1];

           	return new ResponseContainer(acct);  
        }
        catch(Exception e){
			return new ResponseContainer(e.getMessage(),500);
        }


    }

    global class ResponseContainer {
        String message;
        Account acct;
    
      
        ResponseContainer(String message, Integer responseCode) {
            this.message = message;
            RestContext.response.statusCode = responseCode;
        }

        ResponseContainer(Account records){
            this.acct = records;
        }

    }

  
}