objects/Account.object
<CustomObject>
    <fields>
        <fullName>AIMS_Number__c</fullName>
        <description>AIMS Number is a unique customer identifier mastered in Purina ERP (JDE). Globally unique across WinField and Purina.</description>
        <externalId>true</externalId>
        <inlineHelpText>AIMS Number from Purina ERP (JDE)</inlineHelpText>
        <label>AIMS Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit_Key__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WF</fullName>
                </value>
                <value>
                    <fullName>FEED</fullName>
                </value>
                <value>
                    <fullName>DAIRY</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>AddressBook (contact record) number used as a customer identifier and mastered in WinField ERP (JDE). This number makes sense only in the WinField universe.</description>
        <externalId>true</externalId>
        <inlineHelpText>AddressBook number from WinField ERP (JDE)</inlineHelpText>
        <label>Customer Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>App_Code__c</fullName>
        <externalId>true</externalId>
        <label>App Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Connected_App_ID__c</fullName>
        <label>Connected App ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Connected_App__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This indicates if the application does not require a manual provisioning case to be created.</inlineHelpText>
        <label>Does Not Need Manual Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DA_Approval_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Delegated Admin Approval Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>700</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EMS_Application_Object_Name__c</fullName>
        <description>This is the name of the profile, permission set, or custom permission that should be added to the user</description>
        <inlineHelpText>This is the name of the profile, permission set, or custom permission that should be added to the user</inlineHelpText>
        <label>EMS Application Object Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EMS_Application_Type__c</fullName>
        <label>EMS Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Custom Permission</fullName>
                </value>
                <value>
                    <fullName>Permission Set</fullName>
                </value>
                <value>
                    <fullName>Profile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EMS_Application__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EMS Application</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FG_Account_Field__c</fullName>
        <label>FG Account Field</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer_Number__c</fullName>
                </value>
                <value>
                    <fullName>PAES_Number__c</fullName>
                </value>
                <value>
                    <fullName>AIMS_Number__c</fullName>
                </value>
                <value>
                    <fullName>GUID__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FG_Web_service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fine Grain Uses Web Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FG_mgmt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fine-Grained Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_Designation__c</fullName>
        <inlineHelpText>This is the text for a potential group representation, like the AD group.</inlineHelpText>
        <label>Group Designation</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is for the portal site.  It directs the portal on how to use the URLs present in the object.</description>
        <label>Home Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_Delegated_Bypass__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval Queue Can Approve for Del.Admin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Migrated__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Migrated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provisioning_Queue__c</fullName>
        <defaultValue>&quot;Customer_Support&quot;</defaultValue>
        <label>Manual Provisioning Queue</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Use_AD_Role_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Roles Use AD Role Name Attribute</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Cart_Application__c.object
<CustomObject>
    <fields>
        <fullName>Catalog_App__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Related Requests</relationshipLabel>
        <relationshipName>Cart_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UPR_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UPR Number</label>
        <referenceTo>UserProvisioningRequest</referenceTo>
        <relationshipLabel>Cart Applications</relationshipLabel>
        <relationshipName>Cart_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Cart_Entitlement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entilements In Car</relationshipLabel>
        <relationshipName>Requested_FG_Ents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ent_code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entitlement Code</label>
        <referenceTo>Entitlements__c</referenceTo>
        <relationshipName>Entilements_In_Car</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_App__c</fullName>
        <label>Parent App</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cart_Application__c.UPR_Number__c</field>
                <operation>equals</operation>
                <valueField>$Source.RelatedUPR__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cart_Application__c</referenceTo>
        <relationshipLabel>Cart Entitlements</relationshipLabel>
        <relationshipName>Cart_Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Cart Entitlement</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Entitlement In Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entilements In Car</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entitlements__c.object
<CustomObject>
    <fields>
        <fullName>AD_Group_Optional__c</fullName>
        <label>AD Group Optional</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AD_Group__c</fullName>
        <label>AD Group Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ent_Code__c</fullName>
        <label>Entitlement Code</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentApp__c</fullName>
        <label>ParentApp</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Available Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

objects/UserProvFineEntitlement__c.object
<CustomObject>
    <fields>
        <fullName>ParentApp__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>UP Fine Grain Entitlements</relationshipLabel>
        <relationshipName>Fine_Grained_Entitlements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/UserProvisionEntitlement__c.object
<CustomObject>
    <fields>
        <fullName>ParentApp__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>User Provision Entitlements</relationshipLabel>
        <relationshipName>ProvEnts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Provision Entitlement</label>
    <nameField>
        <displayFormat>UPE-{00000000}</displayFormat>
        <label>UserProvisionEntitlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Provision Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UserProvisioningRequest.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>SalesforceUser.Contact.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>User Provisioning Requests</relationshipLabel>
        <relationshipName>User_Provisioning_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overall_Status__c</fullName>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Reason__c</fullName>
        <label>User Reason</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EMSUPRHelper.cls
public class EMSUPRHelper {
    
    private Id uprId {get;set;}
    private Application__c targetApp {get;set;}
    private Set<Entitlements__c> targetEnts {get;set;}
    private UserProvisioningRequest upr {get;set;}
    private List<Cart_Entitlement__c> cartEntsList {get;set;}
    private Set<Account> targetAccts {get;set;}
    
    public EMSUPRHelper(Id uprId, Id appId) {
        uprId = uprId;
        cartEntsList = new List<Cart_Entitlement__c>();
        this.upr = [SELECT connectedAppId, User_Reason__c,SalesforceUserId,operation,state, UserProvAccount.Id,Overall_Status__c FROM UserProvisioningRequest WHERE id = :uprId LIMIT 1];
        targetApp = [Select Id,Name,App_Code__c,Connected_App_ID__c,Connected_App__c,Use_AD_Role_Name__c,DA_Approval_Required__c,Internal_Delegated_Bypass__c,EMS_Application_Object_Name__c,EMS_Application_Type__c,EMS_Application__c,Home_Page__c,Migrated__c,FG_Web_Service__c,FG_mgmt__c,FG_Account_Field__c,Group_Designation__c, Provisioning_Queue__c, Approver__c  from Application__c where Connected_App_ID__c=:appId LIMIT 1];
        Cart_Application__c[] cartApps = [Select Name, Catalog_App__c, (SELECT Id, Ent_Code__c,Account__c,Ent_Code__r.ParentApp__c,RecordType.DeveloperName from Cart_Entitlements__r) from Cart_Application__c where UPR_Number__c=:uprId LIMIT 1];
        if (cartApps != null && cartApps.size()>0){
            Cart_Application__c cartApp = cartApps[0];
            
            targetEnts = new Set<Entitlements__c>();
            targetAccts = new Set<Account>();
            
            Set<Id> cartEntIds = new Set<Id>();
            Set<Id> acctIds = new Set<Id>();
            for (Cart_Entitlement__c cartEnt : cartApp.Cart_Entitlements__r){
                System.debug('Record type:' + cartEnt.RecordType.DeveloperName);
                if (cartEnt.RecordType.DeveloperName != EMSConstants.CART_FG_RT){ //this takes care of the old requests and nulls -- which are coarse grained.
                    cartEntIds.add(cartEnt.Ent_Code__c);
                    
                }
                else{
                    acctIds.add(cartEnt.Account__c);
                }
                cartEntsList.add(cartEnt);
                
            }
            
            for( Entitlements__c targetEnt:[SELECT Description__c,AD_Group_Optional__c,ParentApp__c,AD_Group__c,Ent_Code__c,Id,Name FROM Entitlements__c where Id in :cartEntIds]){
                targetEnts.add(targetEnt);
                
            }
            
            for (Account acct: [SELECT AccountNumber,Active__c,AIMS_Number__c,
            BillingAddress,BillingCity,BillingCountry,BillingPostalCode,BillingState,BillingStreet,
            Business_Unit_Key__c,Customer_Number__c,GUID__c,Id,PAES_Number__c,Name FROM Account where Id in: acctIds]){
                targetAccts.add(acct);
            }
            
        }
        
    }
    
    public UserProvisioningRequest getUPR(){
        return upr;
    }
    
    public String getUserReason(){
        return upr.User_Reason__c;
    }
    
    public String getOperation(){
        return upr.Operation;
    }
    
    public String getState(){
        return upr.State;
    }
    
    public  UserProvAccount getProvisionedAccount(){
        UserProvAccount upa;
        UserProvAccount[] upaList = [SELECT name, externalUserId, externalUsername, externalEmail, externalFirstname, externalLastname, linkState, status FROM UserProvAccount WHERE salesforceUserId = :upr.SalesforceUserId  AND linkState = 'Linked' and ConnectedAppId=:upr.ConnectedAppId];
        if(upaList.size() > 0)
            upa = upaList[0];
        return upa;
    }
    
    public  boolean isEntitlementProvisioned(Id upaId, Id entId){
        UserProvisionEntitlement__c[] provEnts = [SELECT Id from  UserProvisionEntitlement__c where Entitlement_Code__c=:entId and UPA_Parent__c =:upaId];
        if(provEnts.size() >0)
            return true;
        else 
            return false;
        
    }

     public  boolean isAccountProvisioned(Id upaId, Id acctId){
        UserProvFineEntitlement__c[] provEnts = [SELECT Id from UserProvFineEntitlement__c where Entitled_Account__c=:acctId and UPA_Parent__c =:upaId];
        if(provEnts.size() >0)
            return true;
        else 
            return false;
        
    }
    
    public Application__c getUPRApplication(){
        return targetApp;
    }
    
    public Set<Entitlements__c> getUPREntitlements(){ //these are coarse grained entitlements
        return targetEnts;
    }
    
    public Set<Account> getUPRFGEntitlements(){ //these are coarse grained entitlements
        return targetAccts;
    }
    
    public List<Cart_Entitlement__c> getCartEntitlements(){
        return cartEntsList;
    }
    public String getReason(){
        return upr.User_Reason__c;
    }
    
}