objects/Account.object
<CustomObject>
    <fields>
        <fullName>AIMS_Number__c</fullName>
        <description>AIMS Number is a unique customer identifier mastered in Purina ERP (JDE). Globally unique across WinField and Purina.</description>
        <externalId>true</externalId>
        <inlineHelpText>AIMS Number from Purina ERP (JDE)</inlineHelpText>
        <label>AIMS Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Unit_Key__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WF</fullName>
                </value>
                <value>
                    <fullName>FEED</fullName>
                </value>
                <value>
                    <fullName>DAIRY</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>AddressBook (contact record) number used as a customer identifier and mastered in WinField ERP (JDE). This number makes sense only in the WinField universe.</description>
        <externalId>true</externalId>
        <inlineHelpText>AddressBook number from WinField ERP (JDE)</inlineHelpText>
        <label>Customer Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>Composite key that represents a globally unique customer ID. The key is built based on a concatenation of several items.
WinField and Purina: BU designation + AIMS Number
Dairy: Farm ID
Corporate:</description>
        <externalId>true</externalId>
        <label>Globally Unique Customer ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PAES_Number__c</fullName>
        <label>PAES Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>App_Code__c</fullName>
        <externalId>true</externalId>
        <label>App Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ApproverType__c</fullName>
        <label>ApproverType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Connected_App_ID__c</fullName>
        <label>Connected App ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Connected_App__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This indicates if the application does not require a manual provisioning case to be created.</inlineHelpText>
        <label>Does Not Need Manual Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>700</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Group_Designation__c</fullName>
        <inlineHelpText>This is the text for a potential group representation, like the AD group.</inlineHelpText>
        <label>Group Designation</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is for the portal site.  It directs the portal on how to use the URLs present in the object.</description>
        <label>Home Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Migrated__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Migrated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <description>Queue Name</description>
        <label>Queue Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requires_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires Approval</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Cart_Application__c.object
<CustomObject>
    <fields>
        <fullName>Catalog_App__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Related Requests</relationshipLabel>
        <relationshipName>Cart_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UPR_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UPR Number</label>
        <referenceTo>UserProvisioningRequest</referenceTo>
        <relationshipLabel>Cart Applications</relationshipLabel>
        <relationshipName>Cart_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Cart_Entitlement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entilements In Car</relationshipLabel>
        <relationshipName>Requested_FG_Ents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ent_code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entitlement Code</label>
        <referenceTo>Entitlements__c</referenceTo>
        <relationshipName>Entilements_In_Car</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_App__c</fullName>
        <label>Parent App</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cart_Application__c.UPR_Number__c</field>
                <operation>equals</operation>
                <valueField>$Source.RelatedUPR__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cart_Application__c</referenceTo>
        <relationshipLabel>Cart Entitlements</relationshipLabel>
        <relationshipName>Cart_Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RelatedUPR__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>User Provisioning Request</label>
        <referenceTo>UserProvisioningRequest</referenceTo>
        <relationshipLabel>Requested Entitlements</relationshipLabel>
        <relationshipName>uprentitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cart Entitlement</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Entitlement In Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entilements In Car</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entitlements__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ent_Code__c</fullName>
        <label>Entitlement Code</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentApp__c</fullName>
        <label>ParentApp</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Available Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requires_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires Approval</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/UserProvisioningRequest.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>SalesforceUser.Contact.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>User Provisioning Requests</relationshipLabel>
        <relationshipName>User_Provisioning_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Other_Details__c</fullName>
        <label>Other Details</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Overall_Status__c</fullName>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EMSUserAccessProfileTabCntrl.cls
global without sharing class EMSUserAccessProfileTabCntrl {

  public List<Application__c> allApps {get;set;}
    public List<Application__c> provisionedApps {get;set;}
   
    public String selectedApp {get;set;}
    public List<CatalogWrapper> provAppEnts{get;set;}
    public List<CatalogWrapper> pendingApps{get;set;}
    private User user;
    public Id userToRequest{get;set;}
    
  
    
    public EMSUserAccessProfileTabCntrl(){
 
      
  
      
        ApplicationHelper appHelp = new ApplicationHelper();
        allApps = new List<Application__c>();
        provisionedApps = new List<Application__c>();
              allApps = [SELECT Id, Name,Description__c,Connected_App_ID__c from Application__c where isDeleted = false ];
        String message = 'There are ' + allApps.size() + ' applications in all.';
     
        System.debug('user id: '+getCurrentUser());
        userToRequest = getCurrentUser();
        try{
            provAppEnts = appHelp.getProvisionedAppsEntsAsCataLogWrapper(getCurrentUser(),false);
            pendingApps = getPendingRequests();



       // avalAppEnts = appHelp.getAvailableSFAppsAsCataLogWrapper(UserInfo.getUserId());
        }
        catch(Exception e){

             ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'There was a problem initializing the page.'+ e);
            ApexPages.addMessage(msg);
        }
      
  
    }
    
   
    public String getCurrentUser(){
        return ApexPages.currentPage().getParameters().get('sfdc.userId');

    }
    

	public List<CatalogWrapper> getPendingRequests(){
		Set<String> ids2 = new Set<String>();
		Set<String> ids = new Set<String>();
		  List<CatalogWrapper> cwList = new List<CatalogWrapper>();
          Map<Id,String> uprToOperationMap = new Map<Id,String>();
    	List<UserProvisioningRequest> uprs = [SELECT Id, ConnectedAppId,Operation from UserProvisioningRequest where SalesforceUserId=:getCurrentUser()  
            and (overall_status__c = 'Processing' or overall_status__c = 'New' or State='New') and State <> 'Failed' and Application__r.Name <> 'LoL Active Directory'];
    	for (UserProvisioningRequest urp: uprs){
    		ids2.add(urp.Id);
    		ids.add(urp.ConnectedAppId);
            uprToOperationMap.put(urp.Id,urp.Operation);

    	}

    	List<Application__c> apps = [SELECT ApproverType__c,Queue_Name__c,Id, Name,Description__c,App_Code__c,Connected_App_ID__c,Home_Page__c,Group_Designation__c,Connected_App__c,Migrated__c,Approver__c,Requires_Approval__c from Application__c where isDeleted = false and Connected_App_Id__c  in:ids ORDER BY Name ASC NULLS FIRST];
    
    	System.debug('Found ' + apps.size() + ' apps for the user.');
    	for (Application__c app: apps){

    		Cart_Application__C parentCApp = [SELECT ID,UPR_Number__C from Cart_Application__C where Catalog_App__c =:app.Id and UPR_Number__c in:ids2 LIMIT 1];
            System.debug('found parentid: '+ parentCApp.Id);
       		Entitlements__c[] provEnts = [SELECT Id,Ent_Code__c,Name from  Entitlements__c where Id in (SELECT Ent_Code__c from Cart_Entitlement__c where Parent_App__c=:parentCApp.Id and RelatedUPR__c in:ids2)];
         List<Account> accts = [sELECT AccountNumber,Active__c,AIMS_Number__c,AnnualRevenue,
            BillingAddress,BillingCity,BillingCountry,BillingPostalCode,BillingState,BillingStreet,
            Business_Unit_Key__c,Customer_Number__c,GUID__c,Id,PAES_Number__c,Name 
            FROM Account 
            where Id in (SELECT Account__c from Cart_Entitlement__c where Parent_App__c=:parentCApp.Id and RelatedUPR__c in:ids2)];  
   
       		List<Entitlements__c> nullEnts = new List<Entitlements__c>();
            CatalogWrapper cw = new CatalogWrapper(app,provEnts,nullEnts,uprToOperationMap.get(parentCApp.UPR_Number__c));
            cw.provAccounts = accts;
            cw.isGranted = true;
            cw.requestName = parentCApp.UPR_Number__c;
            cwList.add(cw);
        }
        return cwList;


    }

    
@remoteAction
    global static String cancelRequest(String uprNumber){
        
        System.debug('about to cancel request:'+uprNumber);
        UserProvisioningRequest upr = [SELECT Id, Name, State, Other_Details__c from UserProvisioningRequest where id=:uprNumber LIMIT 1];
        upr.Other_Details__c = upr.Other_Details__c +'\n Request has been cancelled by ' + UserInfo.getName() + ' on ' + system.today().format();
        upr.State = 'Completed';
        update upr;

        return 'Successfully cancelled Request# ' + upr.Name;
    }

@remoteAction
    global static String deleteRequest(String uprNumber){
        
        System.debug('about to cancel request:'+uprNumber);

        Cart_Application__c[] cartApps = [Select Name, Catalog_App__c, (SELECT Id, Ent_Code__c,Ent_Code__r.ParentApp__c from Cart_Entitlements__r) from Cart_Application__c where UPR_Number__c=:uprNumber LIMIT 1];
        if (cartApps != null && cartApps.size()>0){
            Cart_Application__c cartApp = cartApps[0];
            
            
            Cart_Entitlement__c[] cartEnts = cartApp.Cart_Entitlements__r;
            if (cartEnts != null && cartEnts.size()>0) delete cartEnts;
            delete cartApps;
        }

        UserProvisioningRequest upr = [SELECT Id, Name, State, Other_Details__c from UserProvisioningRequest where id=:uprNumber LIMIT 1];
       
        delete upr;

        return 'Successfully deleted Request# ' + upr.Name;
    }

    public PageReference reset(){
  
        return null;
    }
}