objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>AddressBook (contact record) number used as a customer identifier and mastered in WinField ERP (JDE). This number makes sense only in the WinField universe.</description>
        <externalId>true</externalId>
        <inlineHelpText>AddressBook number from WinField ERP (JDE)</inlineHelpText>
        <label>Customer Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>Composite key that represents a globally unique customer ID. The key is built based on a concatenation of several items.
WinField and Purina: BU designation + AIMS Number
Dairy: Farm ID
Corporate:</description>
        <externalId>true</externalId>
        <label>Globally Unique Customer ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

objects/Agreement__c.object
<CustomObject>
    <recordTypes>
        <fullName>Grower_Agreement</fullName>
        <active>true</active>
        <description>Grower Agreement Record Type.</description>
        <label>Grower Agreement</label>
    </recordTypes>
</CustomObject>

objects/Environment_Record_Ids__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>For storing Agreement Grower Record Type and Ag Tech Agreement document id.</description>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Environment Record Ids</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Grower__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Grower</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Initial_Password__c</fullName>
        <description>Temporary holder of the password requested by the end user.  After the User record is created, the value of this field is cleared out</description>
        <label>Initial Password</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>JobClassification__c</fullName>
        <label>Job Function</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ag Member</fullName>
                </value>
                <value>
                    <fullName>Broker - Foodservice</fullName>
                </value>
                <value>
                    <fullName>Broker - Retail</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Member</fullName>
                </value>
                <value>
                    <fullName>Dairy Member Owner</fullName>
                </value>
                <value>
                    <fullName>Direct Ag Producer</fullName>
                </value>
                <value>
                    <fullName>Farmer</fullName>
                </value>
                <value>
                    <fullName>Member of a Member</fullName>
                </value>
                <value>
                    <fullName>Member Owner</fullName>
                </value>
                <value>
                    <fullName>Momentum Consultant</fullName>
                </value>
                <value>
                    <fullName>Nutritionist</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Retailer Management</fullName>
                </value>
                <value>
                    <fullName>Retailer Operations</fullName>
                </value>
                <value>
                    <fullName>Retailer Sales</fullName>
                </value>
                <value>
                    <fullName>RTech Partner</fullName>
                </value>
                <value>
                    <fullName>Warehousing Partner</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>seed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WinField</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EMSEmailNotificationPageCtrlTest.cls
@isTest
public class EMSEmailNotificationPageCtrlTest {
	@testSetup static void testData() {
        String profileId = [SELECT Id FROM Profile WHERE Name =: Constants.EMS_EXTERNAL_USER LIMIT 1].Id;
        String recTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Grower_Agreement' AND IsActive = true AND SobjectType = 'Agreement__c'].Id;
        
        //Create a pdf Ag Tech Agreement document.
        Document document = new Document();
        document.Body = Blob.valueOf('Ag Tech Agreement document');
        document.ContentType = 'application/pdf';
        document.DeveloperName = 'Test_Ag_Tech_Agreement';
        document.IsPublic = true;
        document.Name = 'Test Ag Tech Agreement';
        document.FolderId = UserInfo.getUserId();
        insert document;
        
        //Create a custom settings.
        List<Environment_Record_Ids__c> envList = new List<Environment_Record_Ids__c>();
        envList.add(new Environment_Record_Ids__c(Name = 'Agreement Grower Record Type', Record_Id__c = recTypeId));
        envList.add(new Environment_Record_Ids__c(Name = 'Agreement Document Id', Record_Id__c = document.Id));        
        Database.insert(envList);
        
        //Create test account.
        Account a = new Account();
        a.Name = 'Test Account';
        a.Customer_Number__c = '7303726';
        a.GUID__c = 'WF718540';
        Database.SaveResult srA = Database.insert(a);
        String accId = srA.getId();
        
        //Create grower test contact.
        Contact newUserContactG = new Contact(
            FirstName = 'TestG',
            Lastname = 'User',
            AccountId = accId,
            Email = 'testg@email.com'
        );
        
        Database.SaveResult srC = Database.insert(newUserContactG);
        
        Database.DMLOptions dlo = new Database.DMLOptions();
        dlo.EmailHeader.triggerUserEmail = false;
        
        //Create grower test user.
        User newUserG = new User();        
        
        newUserG.Username = '9fgxm90ouw@landolakes.com.ems.dev';
        newUserG.Initial_password__c = 'welcome1';
        newUserG.CommunityNickname = '9fgxm90ouw';
        newUserG.ProfileId = profileId;
        newUserG.Email = 'testg@email.com';
        newUserG.Phone = '9999999999';
        newUserG.FirstName = 'TestG';
        newUserG.LastName = 'User';
        newUserG.JobClassification__c = 'Farmer';
        newUserG.seed__c = true;
        newUserG.Grower__c = true;
        newUserG.Alias = '9fgxm90ouw'.substring(0,7);
        newUserG.LocaleSidKey = 'en_US';
        newUserG.EmailEncodingKey = 'UTF-8';
        newUserG.LanguageLocaleKey = 'en_US';
        newUserG.timezonesidkey = 'America/Los_Angeles';
        newUserG.ContactId = srC.getId();
        
        Database.saveresult srU = Database.insert(newUserG, dlo);
    }
    
    @isTest
    static void testPasswordAndAgTechAgreement(){
        List<User> uList = [Select id, Username from User where Username = '9fgxm90ouw@landolakes.com.ems.dev'];
        system.debug('=== UList ===' + uList);
        String keyToken = EMSForgotPasswordCntrl.issueJWT(uList[0].username, 1800);
        
        PageReference pageRef = Page.EMSEmailNotificationPage;
        Test.setCurrentPage(pageRef);
        
        ApexPages.currentPage().getParameters().put('key', keyToken);
        
        EMSEmailNotificationPageCtrl eenp = new EMSEmailNotificationPageCtrl();
        eenp.password = 'Wel@12345';
        eenp.confirmPassword = 'Wel@12345';
        eenp.submit();
        
        eenp.isAgThAgreement = false;
        eenp.subject = '';
        eenp.submit();
    }
}