objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>AddressBook (contact record) number used as a customer identifier and mastered in WinField ERP (JDE). This number makes sense only in the WinField universe.</description>
        <externalId>true</externalId>
        <inlineHelpText>AddressBook number from WinField ERP (JDE)</inlineHelpText>
        <label>Customer Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Ag_Tech_Agreement__c</fullName>
        <formula>Related_External_User__r.Ag_Tech_Agreement__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Ag Tech Agreement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_External_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Customer User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <externalId>true</externalId>
        <label>BusinessLink ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Related_External_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related External User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <externalId>true</externalId>
        <label>BusinessLink ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ag_Tech_Agreement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ag Tech Agreement</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EMSCallout.cls
public class EMSCallout{
    @future(callout = true)
    public static void sendCases(Set<Id> cObjIds){
        List<Case> caseList = [select id, Contact.Account.Name, Contact.Account.Customer_Number__c, Contact.Account.BillingCity, 
            Contact.Account.BillingState, Related_External_User__r.Name, Related_External_User__r.Phone, 
            Related_External_User__r.Email, Related_External_User__r.Ag2Ag_ID__c, Contact.Name, Status, Origin, CaseNumber, Description, 
            Priority, Ag_Tech_Agreement__c from Case where Id =: cObjIds];
        
        if(!caseList.isEmpty() && !Test.isRunningTest())
            SendCasesToCRMCtrl.sendCasesList(caseList);
    }
}