objects/Account.object
<CustomObject>
    <fields>
        <fullName>AIMS_Number__c</fullName>
        <description>AIMS Number is a unique customer identifier mastered in Purina ERP (JDE). Globally unique across WinField and Purina.</description>
        <externalId>true</externalId>
        <inlineHelpText>AIMS Number from Purina ERP (JDE)</inlineHelpText>
        <label>AIMS Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>AddressBook (contact record) number used as a customer identifier and mastered in WinField ERP (JDE). This number makes sense only in the WinField universe.</description>
        <externalId>true</externalId>
        <inlineHelpText>AddressBook number from WinField ERP (JDE)</inlineHelpText>
        <label>Customer Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <description>Composite key that represents a globally unique customer ID. The key is built based on a concatenation of several items.
WinField and Purina: BU designation + AIMS Number
Dairy: Farm ID
Corporate:</description>
        <externalId>true</externalId>
        <label>Globally Unique Customer ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PAES_Number__c</fullName>
        <label>PAES Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>ApproverType__c</fullName>
        <label>ApproverType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>700</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FG_Account_Field__c</fullName>
        <label>FG Account Field</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer_Number__c</fullName>
                </value>
                <value>
                    <fullName>PAES_Number__c</fullName>
                </value>
                <value>
                    <fullName>AIMS_Number__c</fullName>
                </value>
                <value>
                    <fullName>GUID__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <description>Queue Name</description>
        <label>Queue Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Cart_Application__c.object
<CustomObject>
    <fields>
        <fullName>Catalog_App__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Related Requests</relationshipLabel>
        <relationshipName>Cart_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UPR_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UPR Number</label>
        <referenceTo>UserProvisioningRequest</referenceTo>
        <relationshipLabel>Cart Applications</relationshipLabel>
        <relationshipName>Cart_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Cart_Entitlement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entilements In Car</relationshipLabel>
        <relationshipName>Requested_FG_Ents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ent_code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entitlement Code</label>
        <referenceTo>Entitlements__c</referenceTo>
        <relationshipName>Entilements_In_Car</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_App__c</fullName>
        <label>Parent App</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cart_Application__c.UPR_Number__c</field>
                <operation>equals</operation>
                <valueField>$Source.RelatedUPR__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cart_Application__c</referenceTo>
        <relationshipLabel>Cart Entitlements</relationshipLabel>
        <relationshipName>Cart_Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Cart Entitlement</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Entitlement In Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entilements In Car</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entitlements__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ent_Code__c</fullName>
        <label>Entitlement Code</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentApp__c</fullName>
        <label>ParentApp</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Available Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <externalId>true</externalId>
        <label>BusinessLink ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_Fed_Id__c</fullName>
        <externalId>true</externalId>
        <label>Portal Login</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UserProvisioningRequest.object
<CustomObject>
    <fields>
        <fullName>Account_Address__c</fullName>
        <formula>SalesforceUser.Contact.Account.BillingStreet &amp; &quot;, &quot; &amp; SalesforceUser.Contact.Account.BillingCity &amp; &quot;, &quot; &amp; SalesforceUser.Contact.Account.BillingState &amp; &quot;, &quot; &amp; SalesforceUser.Contact.Account.BillingPostalCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <formula>SalesforceUser.Contact.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <formula>SalesforceUser.Ag2Ag_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BusinessLink ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>User Provisioning Requests</relationshipLabel>
        <relationshipName>User_Provisioning_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Collected_Information__c</fullName>
        <label>Collected Information</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Current_Step__c</fullName>
        <label>Current Approval Step</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DA_Approval_needed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Delegated Admin Approval needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DA_Bypass__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Delegated Admin Can Be Bypssed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delegated_Admin_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegated Admin 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approver_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delegated_Admin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegated Admin</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Delegated_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Internal Approval Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_Details__c</fullName>
        <label>Other Details</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Overall_Status__c</fullName>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requestor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Email__c</fullName>
        <formula>SalesforceUser.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Target Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_User_Name__c</fullName>
        <formula>SalesforceUser.FirstName &amp; &quot; &quot; &amp; SalesforceUser.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Reason__c</fullName>
        <label>User Reason</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EMS_DA_Request.cls
public without sharing class EMS_DA_Request {
    
    public static String REQ_ACTION_APPROVE = 'Approve';
    public static String REQ_ACTION_DENY = 'Reject';
    
    public EMS_DA_Request() {
    }
    
    @RemoteAction
    public static UPRWrapper getUPRInfo(String uprId){
        
        UserProvisioningRequest upr = [SELECT Account_Address__c,Account__c,Ag2Ag_ID__c,Application__r.Name, Application__r.Description__c,AppName,ApprovalStatus,collected_Information__c,Comments__c,
                                       ConnectedAppId,CreatedById,CreatedDate,ExternalUserId,Id,LastModifiedById,LastModifiedDate,Name,Operation,Other_Details__c,
                                       Overall_Status__c,Requestor__c,SalesforceUserId,State,SalesforceUser.Name, Application__r.FG_Account_Field__c,
                                       Target_Email__c,Target_User_Name__c,User_Reason__c, SalesforceUser.External_Fed_Id__c
                                       from UserProvisioningRequest where id=:uprId];
        
        UPRWrapper uprW = new UPRWrapper(returnBlankOrVal(upr.SalesforceUser.Name, Constants.SPACE), 
                                         returnBlankOrVal(upr.Application__r.Name, Constants.SPACE), 
                                         returnBlankOrVal(upr.Application__r.Description__c,'N/A'),
                                         upr.Operation,
                                         returnBlankOrVal(upr.User_Reason__c, Constants.SPACE));
        Cart_Application__c[] cartApps = [Select  UPR_Number__c, Name, Catalog_App__c, 
                                          (SELECT Id, Ent_Code__c,Ent_Code__r.ParentApp__c,Ent_Code__r.Name,
                                           Ent_Code__r.Description__c,
                                           Account__r.Customer_Number__c,Account__r.Id,Account__r.AIMS_Number__c,Account__r.PAES_Number__c,Account__r.Name,
                                           Account__r.GUID__c,Account__r.BillingAddress, RecordType.DeveloperName 
                                           from Cart_Entitlements__r) from Cart_Application__c where UPR_Number__c =:upr.Id];
        
        if (cartApps != null && cartApps.size()>0){
            for (Cart_Application__c cartApp:cartApps){
                Cart_Entitlement__c[] cartEnts = cartApp.Cart_Entitlements__r;
                if (cartEnts != null && cartEnts.size()>0){
                    for (Cart_Entitlement__c ent:cartEnts){
                        if (ent.RecordType.DeveloperName == null || ent.RecordType.DeveloperName ==  EMSConstants.CART_CG_RT){
                            uprW.reqRoles.add(new EntWrapper(ent.Ent_code__r.Name,(String.ISBLANK(ent.Ent_code__r.description__c)?' ':ent.Ent_code__r.description__c)));                        
                        } else {
                            String desc2 = '';
                            String appGuid = getAppGUID(upr.Application__r.FG_Account_Field__c,ent.Account__r);
                            if (appGuid == ent.Account__r.GUID__c)
                                desc2 = '(Global ID:'+ent.Account__r.GUID__c +') ' + EMSUPRController.getAddressString(ent.Account__r.BillingAddress);
                            else 
                                desc2 = '(Global ID:'+ent.Account__r.GUID__c +', ' + appGuid +') ' +  EMSUPRController.getAddressString(ent.Account__r.BillingAddress);
                            uprW.reqAccounts.add(new EntWrapper(ent.Account__r.Name,desc2));
                        }
                    }
                }
            }
        }
        List<ProcessInstanceWorkitem> approvals = [select ProcessInstanceId, ProcessInstance.TargetObjectId, 
                                                   ProcessInstance.TargetObject.Name,
                                                   ProcessInstance.TargetObject.Type, ProcessInstance.CreatedBy.Name,
                                                   ProcessInstance.CreatedDate, ProcessInstance.CreatedBy.SmallPhotoUrl,ActorId 
                                                   from ProcessInstanceWorkitem where isDeleted=false and ActorId =:UserInfo.getUserId() and 
                                                   ProcessInstance.status='Pending' and ProcessInstance.TargetObjectId =:upr.Id ];
        System.debug('Approvals: ' + approvals);
        if (approvals != null && approvals.size()>0) uprW.isApprover = true;
        System.debug('User is approver: ' + uprW.isApprover);
        return uprW;
    }
    
 
    
    @RemoteAction
    public static String processRequest(String approverId, String uprId, String action, String comments){
        UserProvisioningRequest upr = [SELECT ConnectedAppId,DA_Approval_needed__c,
            DA_Bypass__c,Delegated_Admin_2__c,Delegated_Admin__c,Internal_Approval__c,Current_Step__c 
            FROM UserProvisioningRequest 
            WHERE Id=:uprId];
        if (upr.Delegated_Admin__c != UserInfo.getUserId() && upr.Delegated_Admin_2__c != UserInfo.getUserId()){
            System.debug('Current user: ' + UserInfo.getUserName() + ' is not an delegated approver: ' + upr.Delegated_Admin__c +' & '+upr.Delegated_Admin_2__c );
            return 'ERROR';
        }
        
        if (action=='Deny') action = EMS_DA_Request.REQ_ACTION_DENY;

        Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
        req.setComments(comments);
        req.setAction(action);
        if (action == EMS_DA_Request.REQ_ACTION_APPROVE) {
            Id nextapproverId =  null;
            ApplicationHelper ah = new ApplicationHelper(upr.ConnectedAppId);
            Application__c targetApp = ah.getApplication();
            if (targetApp.ApproverType__c.equalsIgnoreCase('QUEUE')){
                Group reviewer = [select Id from Group where Type = 'Queue' and DeveloperName=:targetApp.Queue_Name__c limit 1];
                if (reviewer == null){
                    System.debug('There is a big error.  Queue is null. ');
                    return 'ERROR';
                } else {nextapproverId = reviewer.Id;}
            }
            else {nextapproverId = targetApp.Approver__c;}
            if (nextapproverId != null) req.setNextApproverIds(new Id[] {nextapproverId});
        }
        Id workItemId = EMS_DA_Request.getWorkItemId(upr.Id); 
        if(workItemId == null){
            System.debug('There has been an error procesing delegated admin approval. Action:' + action);
            return 'ERROR';
        }else{
            req.setWorkitemId(workItemId);
            // Submit the request for approval
            Approval.ProcessResult result =  Approval.process(req);
        }
        upr.Current_Step__c='INTERNAL';
        update upr;
        return 'SUCCESS';
    }
    
    public  static String getAppGUID(String fieldName, Account acct){
        if (fieldName.equalsIgnoreCase('GUID__C') && !String.isBlank(acct.GUID__c))
            return 'Global ID:'+ acct.GUID__c;
        else if (fieldName.equalsIgnoreCase('Customer_Number__c') && !String.isBlank(acct.Customer_Number__c))
            return 'Customer #:' +acct.Customer_Number__c; 
        else if (fieldName.equalsIgnoreCase('PAES_Number__c') && !String.isBlank(acct.PAES_Number__c))
            return 'PAES #:'+acct.PAES_Number__c; 
        else if (fieldName.equalsIgnoreCase('AIMS_Number__c') && !String.isBlank(acct.AIMS_Number__c))
            return 'AIMS #:'+acct.AIMS_Number__c;
        return fieldName + ' is null';
    }
    
   


    public static Id getWorkItemId(Id targetObjectId){
        Id retVal = null;
        for(ProcessInstanceWorkitem workItem  : [Select p.Id from ProcessInstanceWorkitem p where p.ProcessInstance.TargetObjectId =: targetObjectId]){
            retVal  =  workItem.Id;
        }
        return retVal;
    }
    
    public EMS_DA_Request(EMS_DA_UserList controller) {
    }
    
    
    public class UPRWrapper{
        public String targetUser{get;set;}
        public String appName{get;set;}
        public String appDesc{get;set;}
        public String reqOperation{get;set;}
        public String userComments{get;set;}
        public List<EntWrapper> reqRoles{get;set;}
        public List<EntWrapper> reqAccounts{get;set;}
        public boolean isApprover{get;set;}
        public UPRWrapper(String targetUserIn, String appNameIn,String appDescIn, String reqOperationIn, String userCommentsIn){
            targetUser = targetUserIn;
            appName = appNamein;
            appDesc = appDescIn;
            userComments = userCommentsIn;
            reqOperation = reqOperationIn;
            reqRoles = new List<EntWrapper>();
            reqAccounts = new List<EntWrapper>();
            isApprover = false;
        }
    }
    public class EntWrapper{
        public String name{get;set;}
        public String description{get;set;}
        public EntWrapper(String name, String description){
            this.name = name;
            this.description=description;
        }
    }
    private static String returnBlankOrVal(String str, String returnForNull) {
        return (String.ISBLANK(str)?returnForNull:str);
    }
}