objects/Account.object
<CustomObject>
    <fields>
        <fullName>AIMS_Number__c</fullName>
        <description>AIMS Number is a unique customer identifier mastered in Purina ERP (JDE). Globally unique across WinField and Purina.</description>
        <externalId>true</externalId>
        <inlineHelpText>AIMS Number from Purina ERP (JDE)</inlineHelpText>
        <label>AIMS Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>winfield</fullName>
        <active>true</active>
        <label>WinField</label>
    </recordTypes>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <externalId>true</externalId>
        <label>BusinessLink ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <externalId>true</externalId>
        <label>BusinessLink ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_Fed_Id__c</fullName>
        <externalId>true</externalId>
        <label>Portal Login</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>JobClassification__c</fullName>
        <label>Job Function</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ag Member</fullName>
                </value>
                <value>
                    <fullName>Broker - Foodservice</fullName>
                </value>
                <value>
                    <fullName>Broker - Retail</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Member</fullName>
                </value>
                <value>
                    <fullName>Dairy Member Owner</fullName>
                </value>
                <value>
                    <fullName>Direct Ag Producer</fullName>
                </value>
                <value>
                    <fullName>Farmer</fullName>
                </value>
                <value>
                    <fullName>Member of a Member</fullName>
                </value>
                <value>
                    <fullName>Member Owner</fullName>
                </value>
                <value>
                    <fullName>Momentum Consultant</fullName>
                </value>
                <value>
                    <fullName>Nutritionist</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Retailer Management</fullName>
                </value>
                <value>
                    <fullName>Retailer Operations</fullName>
                </value>
                <value>
                    <fullName>Retailer Sales</fullName>
                </value>
                <value>
                    <fullName>RTech Partner</fullName>
                </value>
                <value>
                    <fullName>Warehousing Partner</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/UserProvisioningServiceQueuable.cls
public with sharing class UserProvisioningServiceQueuable implements Queueable,Database.AllowsCallouts{
    
    
    private String action='';
    private User targetUser;
    private String value;
    
    
    
    public UserProvisioningServiceQueuable(String action, User targetUserIn, String value) {
        this.action = action;
        targetUser = targetUserIn;
        this.value =value;
        
    }
    
    public UserProvisioningServiceQueuable(String action, Id targetUserIn,String value) {
        
        targetUser =  [SELECT id,External_Fed_Id__c, email, usertype, communitynickname, timezonesidkey, languagelocalekey, firstname, lastname, phone, title,
                       street, city, country, postalcode, username,state, localesidkey, mobilephone, extension, fax, contact.email,Ag2Ag_Id__C,jobclassification__c,IsActive,IsPortalEnabled,
                       Contact.Account.Name,Contact.Account.BillingState,Contact.Account.AIMS_Number__c
                       FROM User
                       WHERE id = :targetUserIn];
        this.action=action;
        this.value=value;
        
    }   
    
    
    public void execute(QueueableContext context){
        UserProvisioningService ups = new UserProvisioningService();
        if (action == EMSConstants.CHANGEPASSWORD_ACT){
            ups.changePassword(targetUser,value);
        }
        if (action== EMSConstants.UPDATECONTACT_ACT){
            Contact c = [select Id,Ag2Ag_Id__C,firstname,lastname,email,phone from Contact where Id=:targetUser.contact.Id LIMIT 1];
            ups.changeContact(targetUser.Ag2Ag_id__c,c); 
        }
        if (action == EMSConstants.CREATUSER_ACT){
            String ag2agID = ups.createUser(value, targetUser.firstName, targetUser.lastName, targetUser.email, targetUser.phone, targetUser.Contact.Account.Name, 'Winfield', targetUser.jobClassification__c,targetUser.Contact.Account.AIMS_Number__c,targetuser.Contact.Account.BillingState);
            targetUser.Ag2Ag_ID__C = ag2agID;
            update targetUser;          
        }
        if (action == EMSConstants.DISABLEUSER_ACT){
            ups.disableUser(targetUser);
        }
    }
}