objects/Account.object
<CustomObject>
    <fields>
        <fullName>GUID__c</fullName>
        <description>Composite key that represents a globally unique customer ID. The key is built based on a concatenation of several items.
WinField and Purina: BU designation + AIMS Number
Dairy: Farm ID
Corporate:</description>
        <externalId>true</externalId>
        <label>Globally Unique Customer ID</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>App_Code__c</fullName>
        <externalId>true</externalId>
        <label>App Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>App_Portal_URL__c</fullName>
        <description>Store a Application URL here.  If one exists then the Application will show up in My Links.  If not, then it will be hidden.</description>
        <inlineHelpText>Store a Application URL here.  If one exists then the Application will show up in My Links.  If not, then it will be hidden.</inlineHelpText>
        <label>App Portal URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>App_URL__c</fullName>
        <description>Store a Home Page URL here.  If one exists then the Home Page will show up in My Links.  If not, then it will be hidden.</description>
        <inlineHelpText>Store a Home Page URL here.  If one exists then the Home Page will show up in My Links.  If not, then it will be hidden.</inlineHelpText>
        <label>App URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>ApproverType__c</fullName>
        <label>ApproverType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Base_Access__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field depicts whether or not this is a base access system, like active directory.  This flag is user segment independent -- which means it applies to everyone.</description>
        <inlineHelpText>This field depicts whether or not this is a base access system, like active directory.  This flag is user segment independent -- which means it applies to everyone.</inlineHelpText>
        <label>Base Access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Connected_App_ID__c</fullName>
        <label>Connected App ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Connected_App__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This indicates if the application does not require a manual provisioning case to be created.</inlineHelpText>
        <label>Does Not Need Manual Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>700</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Group_Designation__c</fullName>
        <inlineHelpText>This is the text for a potential group representation, like the AD group.</inlineHelpText>
        <label>Group Designation</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is for the portal site.  It directs the portal on how to use the URLs present in the object.</description>
        <label>Home Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_Group__c</fullName>
        <label>Internal Group</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Migrated__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Migrated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provisioning_Queue__c</fullName>
        <defaultValue>&quot;Customer_Support&quot;</defaultValue>
        <label>Manual Provisioning Queue</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <description>Queue Name</description>
        <label>Queue Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requires_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Application__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This describes if the application is a system application vs a business application.  It usually provisions base-level access.</description>
        <label>System Application</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Entitlements__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ent_Code__c</fullName>
        <label>Entitlement Code</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentApp__c</fullName>
        <label>ParentApp</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Available Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requires_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires Approval</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>External_Fed_Id__c</fullName>
        <externalId>true</externalId>
        <label>Portal Login</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Verify_Hash__c</fullName>
        <label>Verification Hash</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UserProvisionEntitlement__c.object
<CustomObject>
    <fields>
        <fullName>Entitlement_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entitlement Code</label>
        <referenceTo>Entitlements__c</referenceTo>
        <relationshipLabel>User Provision Entitlements</relationshipLabel>
        <relationshipName>CatalogEnt</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentApp__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>User Provision Entitlements</relationshipLabel>
        <relationshipName>ProvEnts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UPA_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Provisioning Account</label>
        <referenceTo>UserProvAccount</referenceTo>
        <relationshipLabel>User Provision Entitlements</relationshipLabel>
        <relationshipName>User_Provision_Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Provision Entitlement</label>
    <nameField>
        <displayFormat>UPE-{00000000}</displayFormat>
        <label>UserProvisionEntitlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Provision Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ApplicationHelperTest.cls
@isTest
private class ApplicationHelperTest {
    @isTest static void testDataRetrieval() {
        Application__c app = createApplication('Test App1010');
        insert app;
        Application__c app2 = createApplication('Test App1001');
        insert app2;
        ApplicationHelper ah = new ApplicationHelper(app.Name);
        Test.startTest();
        System.assert(ah.getName() == 'Test App1010');
        System.assertEquals(ah.needsApproval(),false);
        Test.stopTest();
        ApplicationHelper ah2 = new ApplicationHelper(app.Id);
        
        System.assert(ah2.getName() == '');
        System.assertEquals(ah2.needsApproval(),false);
        
        ApplicationHelper ah3 = new ApplicationHelper(app);
        
        System.assert(ah3.getName() == 'Test App1010');
        System.assertEquals(ah3.needsApproval(),false);
        System.assert(ah3.getQueueName() == 'test');
        System.assert(ah3.isApproverUser() == false);
        System.assert(ah3.isApproverQueue() == true);        
    }
    
    @isTest static void testAppCreation() {
        Test.startTest();
        Application__c app = createApplication('Test App1010');
        insert app;
        List<Application__c> apps1 = new List<Application__c>();
        apps1.add(app);
        ID jobID = System.enqueueJob(new ConnectAppQueueable(apps1, UserInfo.getSessionId()));
        Test.stopTest();
        List<AppmenuItem> apps = [SELECt Id, Label from AppMenuItem where Name=:app.App_code__c];
        
        System.assert(apps.size()==0);
    }
    
    @isTest static void testUserFunctions() {
        Application__c app = createApplication('Test App1010');
        insert app;
        String userN = generateRandomString(4);
        
        Profile profile = [SELECT Id FROM Profile WHERE Name='EMS External User' LIMIT 1];
        List<Account> partnerAccounts = new List<Account>();
        partnerAccounts.add(new Account(Name = 'Testing Communities Company',GUID__c='testingaccountonly'));
        insert partnerAccounts;
        //Create some Contacts because we want to create portal users we are required to provide a corresponding contactId
        List<Contact> partnerContacts = new List<Contact>();
        partnerContacts.add(new Contact(AccountId = partnerAccounts[0].Id, Email = userN+'@landolakes.com.ems.testing', FirstName = userN, LastName = userN));
        insert partnerContacts;
        List<User> newUsers = new List<User>();
        
        User u = new User();
        u.Username = userN+'@landolakes.com.ems.testing';
        u.Email = userN+'@landolakes.com.ems.testing';
        u.FirstName = userN;
        u.LastName = userN;
        u.CommunityNickname = userN;
        u.Phone = '111-222-3333';
        u.ProfileId = profile.Id;
        //u.Verify_Hash__c = generateHash(userN+userN);
        u.Alias = 'test01';
        u.ContactId = partnerContacts[0].Id;
        u.EmailEncodingKey = 'ISO-8859-1';
        u.IsActive = false;
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        u.TimeZoneSidKey = 'America/New_York';
        
        newUsers.add(u);
        insert newUsers;
        // Implement test code
        
        ApplicationHelper ah = new ApplicationHelper();
        
        System.assertEquals(ah.getProvisionedApps(u.Id).size(),0);
        System.assert(ah.getAvailableSFApps(u.Id).size()>0);
        System.assert(ah.getAvailableSFAppsAsCataLogWrapper(u.Id).size() >0);
        System.assert(ah.getProvisionedAppsAsCataLogWrapper(u.Id).size() ==0);
    }
    
    @IsTest(SeeAllData=true)  static void testUPAFunctions(){
        
        Test.startTest();
        Application__c app = new Application__c(name='Testing UPE Traigger', App_Code__c='testingupetrigger');
        insert app;
        List<Entitlements__c> ents = new List<Entitlements__c>();
        Entitlements__c ent = new Entitlements__c(name='Test2',ent_code__c='testingupetrigger / user',parentapp__c=app.Id);
        ents.add(ent);
        insert ents;
        User u = createUser();
        insert u;
        User u2 = [SELECT Id from User where id=:u.Id LIMIT 1];
        UserProvAccount upa = new UserprovAccount();
        upa.ConnectedAppId = app.Connected_App_Id__c;
        upa.SalesforceUserId = u2.Id;
        System.debug('setting the user id:' + u2.Id);
        upa.Status = 'Active';
        upa.LinkState = 'Linked';
        upa.ExternalUserId = u.username;
        insert upa;
        
        UserProvisionEntitlement__c upe = new UserProvisionEntitlement__c();
        upe.UPA_Parent__c = upa.Id;
        upe.entitlement_code__c = ent.Id;
        insert upe;
        
        ApplicationHelper ah = new ApplicationHelper(app.Connected_App_Id__c);
        ah.getAvailableSFApps(u2.Id);
        ah.getAvailableSFApps(u2.Id);
        ah.getProvisionedApps(u2.Id);
        ah.getAvailableSFAppsAsCataLogWrapper(u2.Id);
        Test.stopTest();
        //System.assert(ah.getAvailableSFApps(u2.Id).size()>0);
        //System.assert(ah.getProvisionedApps(u2.Id).size()==1);
        //System.assert(ah.getAvailableSFAppsAsCataLogWrapper(u2.Id).size()>0);
        //System.assert(ah.getProvisionedAppsAsCataLogWrapper(u2.Id).size()>0);
        ah.getProvisionedAppsAsCataLogWrapper(u2.Id,false);
        ah.getProvisionedAppsEntsAsCataLogWrapper(u2.Id,false);
    }
    
    private static User createUser(){
        String userN = generateRandomString(4);
        
        Profile profile = [SELECT Id FROM Profile WHERE Name='EMS External User' LIMIT 1];
        List<Account> partnerAccounts = new List<Account>();
        partnerAccounts.add(new Account(Name = 'Testing Communities Company'+userN,GUID__c='testingaccountonly'+userN));
        insert partnerAccounts;
        //Create some Contacts because we want to create portal users we are required to provide a corresponding contactId
        List<Contact> partnerContacts = new List<Contact>();
        partnerContacts.add(new Contact(AccountId = partnerAccounts[0].Id, Email = userN+'@landolakes.com.ems.testing', FirstName = userN, LastName = userN));
        insert partnerContacts;
        
        User u = new User();
        u.Username = userN+'@landolakes.com.ems.testing';
        u.Email = userN+'@landolakes.com.ems.testing';
        u.FirstName = userN;
        u.LastName = userN;
        u.CommunityNickname = userN;
        u.Phone = '111-222-3333';
        u.ProfileId = profile.Id;
        //u.Verify_Hash__c = generateHash(userN+userN);
        u.Alias = 'test01';
        u.ContactId = partnerContacts[0].Id;
        u.EmailEncodingKey = 'ISO-8859-1';
        u.IsActive = false;
        u.LanguageLocaleKey = 'en_US';
        u.LocaleSidKey = 'en_US';
        u.TimeZoneSidKey = 'America/New_York';
        u.External_Fed_Id__c=userN;
        return u;
    }
    
    
    // Use: Application__c varApplication = UnitTestDataFactory.createApplication();
    private static Application__c createApplication(String nameIn)
    {
        return new Application__c(
            // Id							= '',
            // OwnerId						= '',
            // IsDeleted					= '',
            Name							= nameIn,
            // CreatedDate					= '',
            // CreatedById					= '',
            // LastModifiedDate				= '',
            // LastModifiedById				= '',
            // SystemModstamp				= '',
            // LastActivityDate				= '',
            App_Code__c					= '22'+nameIn,
            // App_Portal_URL__c			= '',
            // App_URL__c					= '',
            // Approver__c					= '',
            // Connected_App_ID__c			= '',
            // Connected_App__c				= '',
            // Description__c				= '',
            // Group_Designation__c			= '',
            // Home_Page__c					= '',
            // Internal_Group__c			= '',
            Requires_Approval__c			= false,
            Migrated__c					= false,
            System_Application__c		= false,
            ApproverType__c				= 'QUEUE',
            Queue_Name__c				= 'test'
            // Provisioning_Queue__c		= '',
            // Base_Access__c				= ''
        );
    }
    
    private static String generateRandomString(Integer len) {
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz1234567890';
        String randStr = '';
        while (randStr.length() < len) {
            Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
            randStr += chars.substring(idx, idx+1);
        }
        return randStr; 
    }
}