objects/AP_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Baseline__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this policy contains an application that is required for other applications to be provisioned, like Active Directory</inlineHelpText>
        <label>Baseline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>This entitlement rule applies to any of the selected business units, in conjunction with the job classifications.</description>
        <label>Business Unit</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Any</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>FGI</fullName>
                </value>
                <value>
                    <fullName>Purina</fullName>
                </value>
                <value>
                    <fullName>WinField</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Classification__c</fullName>
        <description>This entitlement rule applies these job classifications</description>
        <label>Job Function</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ag Member</fullName>
                </value>
                <value>
                    <fullName>Any</fullName>
                </value>
                <value>
                    <fullName>Broker - Foodservice</fullName>
                </value>
                <value>
                    <fullName>Broker - Retail</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Member</fullName>
                </value>
                <value>
                    <fullName>Dairy Member Owner</fullName>
                </value>
                <value>
                    <fullName>Direct Ag Producer</fullName>
                </value>
                <value>
                    <fullName>Farmer</fullName>
                </value>
                <value>
                    <fullName>Member of a Member</fullName>
                </value>
                <value>
                    <fullName>Member Owner</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Retailer Management</fullName>
                </value>
                <value>
                    <fullName>Retailer Operations</fullName>
                </value>
                <value>
                    <fullName>Retailer Sales</fullName>
                </value>
                <value>
                    <fullName>Momentum Consultant</fullName>
                </value>
                <value>
                    <fullName>Nutritionist</fullName>
                </value>
                <value>
                    <fullName>Warehousing Partner</fullName>
                </value>
                <value>
                    <fullName>SureTech Customer</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Access Policy Rule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Policy Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>App_Code__c</fullName>
        <externalId>true</externalId>
        <label>App Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Migrated__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Migrated</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Policy_Artifacts__c.object
<CustomObject>
    <fields>
        <fullName>App_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>App Code</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Provisioning_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entitlement_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Entitlement Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Entitlements__c.ParentApp__c</field>
                <operation>equals</operation>
                <valueField>$Source.App_Code__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Entitlements__c</referenceTo>
        <relationshipLabel>Policy Artifacts</relationshipLabel>
        <relationshipName>Provisioning_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Rule__c</fullName>
        <label>Parent Rule</label>
        <referenceTo>AP_Rule__c</referenceTo>
        <relationshipLabel>Policy Artifacts</relationshipLabel>
        <relationshipName>Policy_Artifacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Policy Artifiacts</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Policy Artifact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Artifacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <externalId>true</externalId>
        <label>BusinessLink ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Corporate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Corporate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>External_Fed_Id__c</fullName>
        <externalId>true</externalId>
        <label>Portal Login</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FGI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FGI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobClassification__c</fullName>
        <label>Job Function</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ag Member</fullName>
                </value>
                <value>
                    <fullName>Broker - Foodservice</fullName>
                </value>
                <value>
                    <fullName>Broker - Retail</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Member</fullName>
                </value>
                <value>
                    <fullName>Dairy Member Owner</fullName>
                </value>
                <value>
                    <fullName>Direct Ag Producer</fullName>
                </value>
                <value>
                    <fullName>Farmer</fullName>
                </value>
                <value>
                    <fullName>Member of a Member</fullName>
                </value>
                <value>
                    <fullName>Member Owner</fullName>
                </value>
                <value>
                    <fullName>Momentum Consultant</fullName>
                </value>
                <value>
                    <fullName>Nutritionist</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Retailer Management</fullName>
                </value>
                <value>
                    <fullName>Retailer Operations</fullName>
                </value>
                <value>
                    <fullName>Retailer Sales</fullName>
                </value>
                <value>
                    <fullName>RTech Partner</fullName>
                </value>
                <value>
                    <fullName>Warehousing Partner</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>lol__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dairy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>purina__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Purina</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>seed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WinField</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EMSEntitlementAssignment.cls
public class EMSEntitlementAssignment {
    
    
    public EMSEntitlementAssignment(){
        
    }
    
    
    @InvocableMethod(label='Assign Entitlements' description='Assigns entitlements to a user based on job classification and business unit.')
    public static void assignEntitlements(List<User> aList){
        //for every new user, find the permission sets needed based on job classification and business unit
        //
        for(User targetUser: aList){
            assignEntitlements(targetUser.Id+'',false);
            
        } 
    }
    
    
    
    
    @future(callout=true)  public static void assignEntitlements(String userId, boolean baseline){
        //for every new user, find the permission sets needed based on job classification and business unit
        
        System.debug('About to evaluate user: ' + userId);
        User targetUser = [SELECT Ag2Ag_ID__c,Name,External_fed_id__c,jobClassification__c,purina__c,lol__c,corporate__c,seed__c,FGI__c,id from User where Id=:userId];
        String jobClass = targetUser.JobClassification__c;
        boolean purina = targetUser.purina__c;
        boolean dairy = targetUser.lol__c;
        boolean winfield = targetUser.seed__c;
        boolean corporate = targetUser.corporate__c;
        boolean fgi = targetUser.FGI__c;
        System.debug('Running the trigger on user ' + targetUser.Name +' with job class: ' + jobClass);
        
        List<AP_Rule__c> appliedRules = [SELECT Id,Business_Unit__c,(select Id, App_Code__r.Name,App_Code__r.App_Code__c, Entitlement_Code__c from Policy_Artifacts__r) from AP_Rule__c where active__c=true and baseline__c =:baseline and Job_Classification__c includes ('Any',:jobClass)];
        List<EMSPolicyArtifactHelper> appsToAssign = new List<EMSPolicyArtifactHelper>();
        for (AP_Rule__c entRule: appliedRules){
            String[] acceptBUs = entRule.Business_Unit__c.split(';');
            String permSet = entRule.Id;
            boolean provision = false;
            for (String bu : acceptBUs){
                System.debug('Accepted bu is: '+bu);
                
                
                if ((bu.equalsIgnoreCase('Any'))
                    || (bu.equalsIgnoreCase('winfield') && winfield)
                    || (bu.equalsIgnoreCase('dairy') && dairy)
                    || (bu.equalsIgnoreCase('purina') && purina)
                    || (bu.equalsIgnoreCase('corporate') && corporate)
                    || (bu.equalsIgnoreCase('fgi') && fgi))
                {    
                    provision=true;
                }
            }
            
            if (provision) {
                  EMSPolicyArtifactHelper polHelper = new EMSPolicyArtifactHelper(entRule);

                for (Policy_Artifacts__c pli : entRule.Policy_Artifacts__r){
                    System.debug('Connected App Name: '+pli.App_Code__r.App_Code__c); 
                    //AppMenuItem appId = [Select ApplicationId from AppMenuitem where Name=:pli.App_Code__r.App_Code__c LIMIT 1];
                    polHelper.addPolicyArtifact(pli);
                   
                    
                }
                 appsToAssign.add(polHelper);

                for (Id polAppId : polHelper.getAppIdsForPolicy()) {
                    Application__c targetApp = polHelper.getApp(polAppId);

                    if (!Boolean.valueOf(targetApp.Migrated__c)) {
                        UserProvisioningService ups = new UserProvisioningService();
                        ups.entitleUser(targetUser,targetApp,polHelper.getEntsforPolicyApp(polAppId));    
                    }         
                  
                   
                } 
            }//end of provision



            
        }//ent of all policies

        ID jobID = System.enqueueJob(new EMSCreateUPRQueueable(appsToAssign,targetUser));
        
    }   


  
    
    public static void assignEntitlementsByUsername(String userId,boolean baseline){
        //for every new user, find the permission sets needed based on job classification and business unit
        //
        System.debug('About to evalutate user: ' + userId);
        
        User targetUser = [SELECT Name,jobClassification__c,External_fed_Id__c,purina__c,lol__c,seed__c,corporate__c,FGI__c,id,Ag2Ag_ID__c from User where username=:userId];
        String jobClass = targetUser.JobClassification__c;
        boolean purina = targetUser.purina__c;
        boolean dairy = targetUser.lol__c;
        boolean winfield = targetUser.seed__c;
        boolean corporate = targetUser.corporate__c;
        boolean fgi = targetUser.FGI__c;
        System.debug('Running the trigger on user ' + targetUser.Name +' with job class: ' + jobClass);
        
        List<AP_Rule__c> appliedRules = [SELECT Id,Business_Unit__c,(select Id, App_Code__r.Name,  App_Code__r.App_Code__c,Entitlement_Code__c from Policy_Artifacts__r) from AP_Rule__c where active__c=true and baseline__c=:baseline and Job_Classification__c includes ('Any',:jobClass)];
        List<EMSPolicyArtifactHelper> appsToAssign = new List<EMSPolicyArtifactHelper>();
        for (AP_Rule__c entRule: appliedRules){
            String[] acceptBUs = entRule.Business_Unit__c.split(';');
            String permSet = entRule.Id;
            boolean provision = false;
            for (String bu : acceptBUs){
                System.debug('Accepted bu is: '+bu);
                
                
                if ((bu.equalsIgnoreCase('Any'))
                    || (bu.equalsIgnoreCase('winfield') && winfield)
                    || (bu.equalsIgnoreCase('dairy') && dairy)
                    || (bu.equalsIgnoreCase('purina') && purina)
                    || (bu.equalsIgnoreCase('corporate') && corporate)
                    || (bu.equalsIgnoreCase('fgi') && fgi))
                {    
                    provision=true;
                }
                
            }

            if (provision) {
                  EMSPolicyArtifactHelper polHelper = new EMSPolicyArtifactHelper(entRule);

                for (Policy_Artifacts__c pli : entRule.Policy_Artifacts__r){
                    System.debug('Connected App Name: '+pli.App_Code__r.App_Code__c); 
                    //AppMenuItem appId = [Select ApplicationId from AppMenuitem where Name=:pli.App_Code__r.App_Code__c LIMIT 1];
                    polHelper.addPolicyArtifact(pli);
                   
                    
                }
                 appsToAssign.add(polHelper);

                for (Id polAppId : polHelper.getAppIdsForPolicy()) {
                    Application__c targetApp = polHelper.getApp(polAppId);

                    if (!Boolean.valueOf(targetApp.Migrated__c)) {
                        UserProvisioningService ups = new UserProvisioningService();
                        ups.entitleUser(targetUser,targetApp,polHelper.getEntsforPolicyApp(polAppId));    
                    }         
                  
                   
                } 
            }//end of provision
         }//for
            ID jobID = System.enqueueJob(new EMSCreateUPRQueueable(appsToAssign,targetUser));
            
        
        
    }   
    
    
}