objects/AP_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Baseline__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this policy contains an application that is required for other applications to be provisioned, like Active Directory</inlineHelpText>
        <label>Baseline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>This entitlement rule applies to any of the selected business units, in conjunction with the job classifications.</description>
        <label>Business Unit</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Any</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>FGI</fullName>
                </value>
                <value>
                    <fullName>Purina</fullName>
                </value>
                <value>
                    <fullName>WinField</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Classification__c</fullName>
        <description>This entitlement rule applies these job classifications</description>
        <label>Job Function</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ag Member</fullName>
                </value>
                <value>
                    <fullName>Any</fullName>
                </value>
                <value>
                    <fullName>Broker - Foodservice</fullName>
                </value>
                <value>
                    <fullName>Broker - Retail</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Member</fullName>
                </value>
                <value>
                    <fullName>Dairy Member Owner</fullName>
                </value>
                <value>
                    <fullName>Direct Ag Producer</fullName>
                </value>
                <value>
                    <fullName>Farmer</fullName>
                </value>
                <value>
                    <fullName>Member of a Member</fullName>
                </value>
                <value>
                    <fullName>Member Owner</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Retailer Management</fullName>
                </value>
                <value>
                    <fullName>Retailer Operations</fullName>
                </value>
                <value>
                    <fullName>Retailer Sales</fullName>
                </value>
                <value>
                    <fullName>Momentum Consultant</fullName>
                </value>
                <value>
                    <fullName>Nutritionist</fullName>
                </value>
                <value>
                    <fullName>Warehousing Partner</fullName>
                </value>
                <value>
                    <fullName>SureTech Customer</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Access Policy Rule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Policy Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>App_Code__c</fullName>
        <externalId>true</externalId>
        <label>App Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Migrated__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Migrated</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Policy_Artifacts__c.object
<CustomObject>
    <fields>
        <fullName>App_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>App Code</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Provisioning_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entitlement_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Entitlement Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Entitlements__c.ParentApp__c</field>
                <operation>equals</operation>
                <valueField>$Source.App_Code__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Entitlements__c</referenceTo>
        <relationshipLabel>Policy Artifacts</relationshipLabel>
        <relationshipName>Provisioning_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Rule__c</fullName>
        <label>Parent Rule</label>
        <referenceTo>AP_Rule__c</referenceTo>
        <relationshipLabel>Policy Artifacts</relationshipLabel>
        <relationshipName>Policy_Artifacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Policy Artifiacts</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Policy Artifact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Artifacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <externalId>true</externalId>
        <label>BusinessLink ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Corporate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Corporate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>External_Fed_Id__c</fullName>
        <externalId>true</externalId>
        <label>Portal Login</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsMassLoaded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMassLoaded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobClassification__c</fullName>
        <label>Job Function</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ag Member</fullName>
                </value>
                <value>
                    <fullName>Broker - Foodservice</fullName>
                </value>
                <value>
                    <fullName>Broker - Retail</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Member</fullName>
                </value>
                <value>
                    <fullName>Dairy Member Owner</fullName>
                </value>
                <value>
                    <fullName>Direct Ag Producer</fullName>
                </value>
                <value>
                    <fullName>Farmer</fullName>
                </value>
                <value>
                    <fullName>Member of a Member</fullName>
                </value>
                <value>
                    <fullName>Member Owner</fullName>
                </value>
                <value>
                    <fullName>Momentum Consultant</fullName>
                </value>
                <value>
                    <fullName>Nutritionist</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Retailer Management</fullName>
                </value>
                <value>
                    <fullName>Retailer Operations</fullName>
                </value>
                <value>
                    <fullName>Retailer Sales</fullName>
                </value>
                <value>
                    <fullName>RTech Partner</fullName>
                </value>
                <value>
                    <fullName>Warehousing Partner</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Provisioned</fullName>
                </value>
                <value>
                    <fullName>Uploaded</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Verify_Hash__c</fullName>
        <label>Verification Hash</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>lol__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dairy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>purina__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Purina</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>seed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WinField</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/NewUsersMassUploadProvisioningBatch.cls
public class NewUsersMassUploadProvisioningBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Username,Ag2Ag_ID__c,Name,External_fed_id__c,jobClassification__c,purina__c,lol__c,corporate__c,seed__c,id,IsMassLoaded__c,Status__c,Verify_Hash__c from User where isActive = true AND IsMassLoaded__c = true AND Status__c = \'Validated\'';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        for(User targetUser : (List<User>)scope){
            try{
                String jobClass = targetUser.JobClassification__c;
                boolean purina = targetUser.purina__c;
                boolean dairy = targetUser.lol__c;
                boolean winfield = targetUser.seed__c;
                boolean corporate = targetUser.corporate__c;
                system.debug('=== jobClass ===' + jobClass);
                List<AP_Rule__c> appliedRules = [SELECT Id,Business_Unit__c,(select Id, App_Code__r.Name,App_Code__r.App_Code__c, Entitlement_Code__c from Policy_Artifacts__r) from AP_Rule__c where active__c=true and baseline__c=true and Job_Classification__c includes ('Any',:jobClass)];
                system.debug('=== appliedRules ===' + appliedRules);
                List<EMSPolicyArtifactHelper> appsToAssign = new List<EMSPolicyArtifactHelper>();
                for (AP_Rule__c entRule: appliedRules){
                    String[] acceptBUs = entRule.Business_Unit__c.split(';');
                    String permSet = entRule.Id;
                    boolean provision = false;
                    for (String bu : acceptBUs){
                        if ((bu.equalsIgnoreCase('Any'))
                            || (bu.equalsIgnoreCase('winfield') && winfield)
                            || (bu.equalsIgnoreCase('dairy') && dairy)
                            || (bu.equalsIgnoreCase('purina') && purina)
                            || (bu.equalsIgnoreCase('corporate') && corporate))
                        {    
                            provision=true;
                        }
                    }
                    
                    if (provision) {
                        EMSPolicyArtifactHelper polHelper = new EMSPolicyArtifactHelper(entRule);
                        for (Policy_Artifacts__c pli : entRule.Policy_Artifacts__r){
                            polHelper.addPolicyArtifact(pli);
                        }
                        appsToAssign.add(polHelper);
                        system.debug('=== appsToAssign ===' + appsToAssign);
                        for (Id polAppId : polHelper.getAppIdsForPolicy()) {
                            Application__c targetApp = polHelper.getApp(polAppId);
                            system.debug('=== targetApp ===' + targetApp);
                            if (!Boolean.valueOf(targetApp.Migrated__c)) {
                                UserProvisioningService ups = new UserProvisioningService();
                                if(!Test.isRunningTest())
                                    ups.entitleUser(targetUser,targetApp,polHelper.getEntsforPolicyApp(polAppId));    
                            }         
                        } 
                    }//end of provision
                }//ent of all policies
                if(!Test.isRunningTest()){
                    System.enqueueJob(new EMSCreateUPRQueueable(appsToAssign,targetUser));
                }
                
                targetUser.Status__c = 'Provisioned';
                
                Database.update(targetUser);
            }
            catch(Exception e){}
        }
    }

    public void finish(Database.BatchableContext BC){}    
}