objects/AP_Rule__c.object
<CustomObject>
    <label>Access Policy Rule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Policy Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>App_Code__c</fullName>
        <externalId>true</externalId>
        <label>App Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ApproverType__c</fullName>
        <label>ApproverType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Connected_App_ID__c</fullName>
        <label>Connected App ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DA_Approval_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Delegated Admin Approval Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EMS_Application_Object_Name__c</fullName>
        <description>This is the name of the profile, permission set, or custom permission that should be added to the user</description>
        <inlineHelpText>This is the name of the profile, permission set, or custom permission that should be added to the user</inlineHelpText>
        <label>EMS Application Object Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EMS_Application_Type__c</fullName>
        <label>EMS Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Custom Permission</fullName>
                </value>
                <value>
                    <fullName>Permission Set</fullName>
                </value>
                <value>
                    <fullName>Profile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EMS_Application__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EMS Application</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FG_Account_Field__c</fullName>
        <label>FG Account Field</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer_Number__c</fullName>
                </value>
                <value>
                    <fullName>PAES_Number__c</fullName>
                </value>
                <value>
                    <fullName>AIMS_Number__c</fullName>
                </value>
                <value>
                    <fullName>GUID__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FG_Default_user_acct__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default User Account for FG</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FG_Filter_prefix__c</fullName>
        <label>Fine-Grain Filter prefix</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FD</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>WF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FG_Instructions__c</fullName>
        <label>External User Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FG_Max_Ents__c</fullName>
        <label>Number of FG Ents Allowed Per Account</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FG_Search_Filter__c</fullName>
        <label>FG Search Filter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Use User Account Search Filter</fullName>
                </value>
                <value>
                    <fullName>Use Parent Account Search Filter</fullName>
                </value>
                <value>
                    <fullName>No Validation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FG_Web_service__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fine Grain Uses Web Service</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FG_mgmt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fine-Grained Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_Designation__c</fullName>
        <inlineHelpText>This is the text for a potential group representation, like the AD group.</inlineHelpText>
        <label>Group Designation</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is for the portal site.  It directs the portal on how to use the URLs present in the object.</description>
        <label>Home Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_Delegated_Bypass__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval Queue Can Approve for Del.Admin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Migrated__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Migrated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Needs_Role__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This determines if there is an approval process if no roles are on the request</description>
        <inlineHelpText>This determines if there is an approval process if no roles are on the request</inlineHelpText>
        <label>Needs A Role</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <description>Queue Name</description>
        <label>Queue Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requires_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires Approval</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Entitlements__c.object
<CustomObject>
    <fields>
        <fullName>AD_Group_Optional__c</fullName>
        <label>AD Group Optional</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AD_Group__c</fullName>
        <label>AD Group Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ent_Code__c</fullName>
        <label>Entitlement Code</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentApp__c</fullName>
        <label>ParentApp</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Available Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requires_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires Approval</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Policy_Artifacts__c.object
<CustomObject>
    <fields>
        <fullName>App_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>App Code</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Provisioning_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entitlement_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Entitlement Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Entitlements__c.ParentApp__c</field>
                <operation>equals</operation>
                <valueField>$Source.App_Code__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Entitlements__c</referenceTo>
        <relationshipLabel>Policy Artifacts</relationshipLabel>
        <relationshipName>Provisioning_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Policy Artifiacts</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Policy Artifact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Policy Artifacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EMSPolicyArtifactHelper.cls
public class EMSPolicyArtifactHelper {

    private Map<Application__c,Set<Entitlements__c>> policyArtifacts {get;set;}
    private Map<Id,Application__c> appList {get;set;}
    private Map<Id,Entitlements__c> entList {get;set;}
    private AP_Rule__c policyId;


    public EMSPolicyArtifactHelper() {

        this.policyArtifacts = new Map<Application__c,Set<Entitlements__c>>();
        this.appList = new Map<Id,Application__c>();
        this.entList = new Map<Id,Entitlements__c>();
        
    }

  public EMSPolicyArtifactHelper(AP_Rule__c policyIdIn) {

        this.policyArtifacts = new Map<Application__c,Set<Entitlements__c>>();
        this.appList = new Map<Id,Application__c>();
        this.entList = new Map<Id,Entitlements__c>();
        this.policyId =policyIdIn;
    }

    public void addPolicyArtifact(Policy_Artifacts__c polArt){

        Application__c app = appList.get(polArt.App_Code__r.Id);
        Entitlements__c ent;
        if (app == null){
            app = [Select ApproverType__c,Queue_Name__c,Name,App_Code__c,Internal_Delegated_Bypass__c,Connected_App_ID__c,Home_Page__c,Migrated__c,Group_Designation__c, Needs_Role__c,
            DA_Approval_Required__c,EMS_Application_Object_Name__c,EMS_Application_Type__c,EMS_Application__c,
            FG_Default_user_acct__c,FG_Filter_prefix__c,FG_Instructions__c,FG_Max_Ents__c,FG_mgmt__c,FG_Search_Filter__c,FG_Account_Field__c, FG_Web_service__c,
            Approver__c,Requires_Approval__c  from Application__c where App_Code__c=:polArt.App_Code__r.App_Code__c LIMIT 1];
            appList.put(app.Id, app);
            policyArtifacts.put(app,null);
        }
        if (polArt.Entitlement_Code__c != null){
            ent = entList.get(polArt.Entitlement_Code__c);
            System.debug('The entitlement code is: '+ polArt.Entitlement_Code__c);
            if (ent == null){
                ent = [SELECT AD_Group_Optional__c,AD_Group__c,Approver__c,Ent_Code__c,Id,Name,ParentApp__c,Requires_Approval__c FROM Entitlements__c where Id=:polArt.Entitlement_Code__c LIMIT 1];
                entList.put(ent.Id,ent);
            }

            Set<Entitlements__c> setEnts = policyArtifacts.get(app);
            if (setEnts == null){
                setEnts = new Set<Entitlements__c>();
            }
            setEnts.add(ent);
            policyArtifacts.put(app,setEnts);
        }

    }

    public Set<Entitlements__c> getEntsforPolicyApp(Id appId){
        Application__c app = appList.get(appId);
        return policyArtifacts.get(app);
        
    }

    public Set<Id> getAppIdsForPolicy(){
        return appList.keySet();
    }

    public Application__c getApp(Id appId){
        return appList.get(appId);
    }

    public AP_Rule__c getPolicyId(){
        return policyId;
    }

}