objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>App_Code__c</fullName>
        <externalId>true</externalId>
        <label>App Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>700</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

objects/Cart_Application__c.object
<CustomObject>
    <fields>
        <fullName>Catalog_App__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Related Requests</relationshipLabel>
        <relationshipName>Cart_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UPR_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UPR Number</label>
        <referenceTo>UserProvisioningRequest</referenceTo>
        <relationshipLabel>Cart Applications</relationshipLabel>
        <relationshipName>Cart_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Cart_Entitlement__c.object
<CustomObject>
    <fields>
        <fullName>Ent_code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entitlement Code</label>
        <referenceTo>Entitlements__c</referenceTo>
        <relationshipName>Entilements_In_Car</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_App__c</fullName>
        <label>Parent App</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cart_Application__c.UPR_Number__c</field>
                <operation>equals</operation>
                <valueField>$Source.RelatedUPR__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cart_Application__c</referenceTo>
        <relationshipLabel>Cart Entitlements</relationshipLabel>
        <relationshipName>Cart_Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RelatedUPR__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>User Provisioning Request</label>
        <referenceTo>UserProvisioningRequest</referenceTo>
        <relationshipLabel>Requested Entitlements</relationshipLabel>
        <relationshipName>uprentitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cart Entitlement</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Entitlement In Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entilements In Car</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entitlements__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ent_Code__c</fullName>
        <label>Entitlement Code</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentApp__c</fullName>
        <label>ParentApp</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Available Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

objects/UserProvisioningRequest.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>User Provisioning Requests</relationshipLabel>
        <relationshipName>User_Provisioning_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EMSGeneralTriggerTest.cls
@isTest
private class EMSGeneralTriggerTest {
	
	@isTest static void testApplicationTrigger() {
		Test.startTest();
		Application__c app =  new Application__c(name='Test1__test1',app_code__c='123123',Description__C='Test');
        insert app;
        Test.stopTest();

	}
	
	@isTest(SeeAllData=true) static void testCartEntitlementTrigger() {
		Test.startTest();
		Application__c app =  new Application__c(name='Test1__test1',app_code__c='123123',Description__C='Test');
        insert app;
         Entitlements__c ent = new Entitlements__c(name='Test2',ent_code__c='testingupetrigger / user',parentapp__c=app.Id);
         insert ent;
		UserProvisioningRequest upr = new UserProvisioningRequest();

        upr.ExternalUserId = 'test111';
        upr.ApprovalStatus = 'NotRequired';
        //upr.ConnectedAppId = [SELECT Id from AppMenuItem LIMIT 1].Id;
        upr.AppName = app.Name;
        upr.Application__c = app.Id;
        upr.Operation ='Create';
        upr.State='New';
        upr.SalesforceUserId = [SELECT ID from user where isActive = true LIMIT 1].Id;
		insert upr;
		Cart_Application__c capp = new Cart_Application__c();
		capp.UPR_Number__c = upr.Id;
		capp.Catalog_App__c = app.Id;
		insert capp;

		Cart_Entitlement__c cent = new Cart_Entitlement__C();
		cent.RelatedUPR__c = upr.Id;
		cent.ent_code__c = ent.Id;
		//cent.Parent_app__c = capp.Id;
		insert cent;
		Test.stopTest();

		
	}
	
}