objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>App_Code__c</fullName>
        <externalId>true</externalId>
        <label>App Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>App_URL__c</fullName>
        <description>Store a Home Page URL here.  If one exists then the Home Page will show up in My Links.  If not, then it will be hidden.</description>
        <inlineHelpText>Store a Home Page URL here.  If one exists then the Home Page will show up in My Links.  If not, then it will be hidden.</inlineHelpText>
        <label>App URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Connected_App_ID__c</fullName>
        <label>Connected App ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

classes/UpdateAppQueueable.cls
public class UpdateAppQueueable implements Queueable{

	public UpdateAppQueueable() {
		
	}

	public void execute(QueueableContext context){
		    Application__c[] apps = [SELECT Id,Name, App_URL__c, Connected_App_ID__c, App_Code__c from Application__c where Connected_App_ID__c = null LIMIT 30];
     
        for(Application__c app:apps){

        AppMenuItem[] amis = [SELECT Id, ApplicationId from AppMenuItem where name=:app.App_Code__c limit 1];
        if (amis != null && amis.size() >0){
            app.Connected_App_ID__c = amis[0].ApplicationId;
            update app;

            }
        }
	}

}