objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>App_Code__c</fullName>
        <externalId>true</externalId>
        <label>App Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ApproverType__c</fullName>
        <label>ApproverType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Children_allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Child Accounts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Connected_App_ID__c</fullName>
        <label>Connected App ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Connected_App__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This indicates if the application does not require a manual provisioning case to be created.</inlineHelpText>
        <label>Does Not Need Manual Steps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DA_Approval_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Delegated Admin Approval Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>700</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FG_Default_user_acct__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default User Account for FG</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FG_Filter_prefix__c</fullName>
        <label>Fine-Grain Filter prefix</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>FD</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>WF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FG_Instructions__c</fullName>
        <label>External User Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FG_Max_Ents__c</fullName>
        <label>Number of FG Ents Allowed Per Account</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FG_Search_Filter__c</fullName>
        <label>FG Search Filter</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Use User Account Search Filter</fullName>
                </value>
                <value>
                    <fullName>Use Parent Account Search Filter</fullName>
                </value>
                <value>
                    <fullName>No Validation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FG_mgmt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fine-Grained Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_Designation__c</fullName>
        <inlineHelpText>This is the text for a potential group representation, like the AD group.</inlineHelpText>
        <label>Group Designation</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is for the portal site.  It directs the portal on how to use the URLs present in the object.</description>
        <label>Home Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_Delegated_Bypass__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approval Queue Can Approve for Del.Admin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Migrated__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Migrated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Needs_Role__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This determines if there is an approval process if no roles are on the request</description>
        <inlineHelpText>This determines if there is an approval process if no roles are on the request</inlineHelpText>
        <label>Needs A Role</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <description>Queue Name</description>
        <label>Queue Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requires_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires Approval</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <externalId>true</externalId>
        <label>BusinessLink ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email_Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Manager_Email__c</fullName>
        <label>Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Manager_Name__c</fullName>
        <label>Manager Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_Phone__c</fullName>
        <label>Manager Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Request_Field__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Request Fields</relationshipLabel>
        <relationshipName>Request_Fields</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field_Label__c</fullName>
        <label>Field Label</label>
        <length>60</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                    <label>Text</label>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Save_To_Object__c</fullName>
        <label>Save To Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request Field</label>
    <nameField>
        <displayFormat>Field-{0000}</displayFormat>
        <label>Request Field Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <externalId>true</externalId>
        <label>BusinessLink ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>BYOID__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Login name is email address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Corporate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Corporate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>External_Fed_Id__c</fullName>
        <externalId>true</externalId>
        <label>Portal Login</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Grower__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Grower</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobClassification__c</fullName>
        <label>Job Function</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ag Member</fullName>
                </value>
                <value>
                    <fullName>Broker - Foodservice</fullName>
                </value>
                <value>
                    <fullName>Broker - Retail</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Member</fullName>
                </value>
                <value>
                    <fullName>Dairy Member Owner</fullName>
                </value>
                <value>
                    <fullName>Direct Ag Producer</fullName>
                </value>
                <value>
                    <fullName>Farmer</fullName>
                </value>
                <value>
                    <fullName>Member of a Member</fullName>
                </value>
                <value>
                    <fullName>Member Owner</fullName>
                </value>
                <value>
                    <fullName>Momentum Consultant</fullName>
                </value>
                <value>
                    <fullName>Nutritionist</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Retailer Management</fullName>
                </value>
                <value>
                    <fullName>Retailer Operations</fullName>
                </value>
                <value>
                    <fullName>Retailer Sales</fullName>
                </value>
                <value>
                    <fullName>RTech Partner</fullName>
                </value>
                <value>
                    <fullName>Warehousing Partner</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Manager_Email__c</fullName>
        <formula>Contact.Manager_Email__c</formula>
        <label>Manager Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_Name__c</fullName>
        <formula>Contact.Manager_Name__c</formula>
        <label>Manager Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_Phone__c</fullName>
        <formula>Contact.Manager_Phone__c</formula>
        <label>Manager Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>lol__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dairy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>purina__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Purina</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>seed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WinField</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ExternalRequestCntrl.cls
global without sharing class ExternalRequestCntrl {
    
    public ExternalRequestCntrl() {
    }
    
    public ExternalRequestCntrl(EMSHomeCntrl controller) {
    }
    
    @RemoteAction
    global static List<AccountWrapper> fetchAccountsForRequest(String appId, String cUserId){
        if(cUserId == null || String.isBlank(cUserId)){
            cUserId = UserInfo.getUserId();
        }
        List<AccountWrapper> accts = new List<AccountWrapper>();
        Id connAppId = [SELECT Connected_App_Id__c from Application__c where Id=:appId].Connected_App_Id__c;
        ApplicationHelper ah = new ApplicationHelper(connAppId);
        for(Account acc : ah.getFineGrainAccounts(cUserId,false)) {
            String accNo = String.isNotBlank(ah.getAppGUIDValue(acc)) ? ah.getAppGUIDValue(acc) : Constants.EMPTY;
            String addrs = (acc.BillingAddress != null) ? getAddressString(acc.BillingAddress) : Constants.EMPTY;
            accts.add(new AccountWrapper(acc.Name,addrs,accNo));
        }
        return accts;
    }
    
    @RemoteAction
    global static List<RequestField> prepopRequestFields(String appId,String cUserId){
        if(cUserId == null || String.isBlank(cUserId)){
            cUserId = UserInfo.getUserId();
        }
        List<RequestField> rfs = new List<RequestField>();
        List<Request_Field__c> rfcs = [SELECT Field_Label__c,Save_To_Object__c,Field_Type__c,Required__c,Field_Name__c FROM Request_Field__c WHERE Application__c =:appId ORDER BY Order__c];
        
        SObject soUser = [SELECT Ag2Ag_ID__c,Alias,BYOID__c,City,CommunityNickname,Manager_Email__c,Manager_Name__c,Manager_Phone__c, 
                          CompanyName,ContactId,Corporate__c,Country,Department,Email,Email_Verified__c,
                          Extension,Fax,FirstName,Grower__c,Id,JobClassification__c,LastName,lol__c,ManagerId,
                          MobilePhone,Name,Phone,PostalCode,purina__c,seed__c,State,Street,Title,
                          Username
                          FROM User where Id=:cUserId];
        
        SObject soContact = [SELECT Ag2Ag_ID__c,AssistantName,AssistantPhone,Birthdate,Department,Manager_Email__c,Manager_Name__c,Manager_Phone__c, 
                             Description,Email,MailingAddress,MailingCity,MailingCountry,MailingPostalCode,MailingState,MailingStreet,
                             Manager__c,MobilePhone,Phone,Salutation,Title 
                             FROM Contact where Id =:(Id)soUser.get('ContactId')];
        for(Request_Field__c rfc:rfcs){
            RequestField rf = new RequestField();
            rf.value = '';
            if( rfc.Save_To_Object__c != null && rfc.Save_To_Object__c.equalsIgnoreCase('User')){
                rf.value = (String)soUser.get(rfc.Field_Name__c);
            } else if( rfc.Save_To_Object__c != null && rfc.Save_To_Object__c.equalsIgnoreCase('Contact')){
                rf.value = (String)soContact.get(rfc.Field_Name__c);
            }
            if(rf.value == null) rf.value = Constants.EMPTY;
            rf.Id = rfc.Field_Label__c;
            rf.rfId = rfc.Id;
            rf.fieldType = rfc.Field_Type__c;
            rf.required = rfc.Required__c;
            rfs.add(rf);
        }
        return rfs;
    }
    
    public static SObject getNewSobject(String gett,String objId) {
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe(); 
        Schema.SObjectType st = gd.get(gett);
        Sobject s = st.newSobject((ID)objId);
        return s;
    }
    
    @RemoteAction
    global static void submitRequest(String appId, List<AccountWrapper> accounts, List<RequestField> requestInfo, String comments, String cUserId){
        if(cUserId == null || String.isBlank(cUserId)){
            cUserId = UserInfo.getUserId();
        }
        Application__c app  = [SELECT Children_allowed__c,ApproverType__c,Migrated__c,Connected_App_ID__c,Queue_Name__c,Group_Designation__c,Home_Page__c,Approver__c,
                               DA_Approval_Required__c,Internal_Delegated_Bypass__c,Description__c,App_Code__c,Connected_App__c,Id,IsDeleted,Name,OwnerId,Requires_Approval__c,Needs_Role__c,
                               FG_Default_user_acct__c,FG_Filter_prefix__c,FG_Instructions__c,FG_Max_Ents__c,FG_mgmt__c,FG_Search_Filter__c 
                               FROM Application__c WHERE Id=:appId LIMIT 1];
        User targetUser = [SELECT Id, FirstName, LastName,External_fed_id__c,Ag2Ag_ID__c FROM User WHERE isActive = true AND Id = :cUserId LIMIT 1];
        if (!Boolean.valueOf(app.Migrated__c)) {
            UserProvisioningService ups = new UserProvisioningService();
            try{
                ups.entitleUser(targetUser,app,null,requestInfo+''); 
            }catch(Exception e){
            }
        } else{
            ID jobID = System.enqueueJob(new EMSCreateUPRQueueable(app,targetuser,comments,requestInfo,accounts,cUserId,'Create'));
        }
    }
    public static String getAddressString(Address addy){
        String assignedTo = (String.isNotBlank(addy.getStreet()) ? addy.getStreet()+ Constants.COMMA + Constants.SPACE : Constants.EMPTY) + 
            (String.isNotBlank(addy.getCity()) ? addy.getCity()+ Constants.COMMA + Constants.SPACE : Constants.EMPTY) + 
            (String.isNotBlank(addy.getState()) ? addy.getState()+ Constants.SPACE : Constants.EMPTY) + 
            (String.isNotBlank(addy.getPostalCode()) ? String.valueOf(addy.getPostalCode())+ Constants.COMMA + Constants.SPACE : Constants.EMPTY) +
            (String.isNotBlank(addy.getCountry()) ? addy.getCountry() : Constants.EMPTY);
        assignedTo = assignedTo.trim().removeEnd(',');
        return assignedTo;
    }
}