objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>App_Code__c</fullName>
        <externalId>true</externalId>
        <label>App Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ApproverType__c</fullName>
        <label>ApproverType</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Queue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business__c</fullName>
        <label>Business Unit</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Dairy</fullName>
                </value>
                <value>
                    <fullName>Purina</fullName>
                </value>
                <value>
                    <fullName>WinField</fullName>
                </value>
                <value>
                    <fullName>FGI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Children_allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Child Accounts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Connected_App_ID__c</fullName>
        <label>Connected App ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>700</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FG_Instructions__c</fullName>
        <label>External User Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FG_Max_Ents__c</fullName>
        <label>Number of FG Ents Allowed Per Account</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FG_mgmt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fine-Grained Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Group_Designation__c</fullName>
        <inlineHelpText>This is the text for a potential group representation, like the AD group.</inlineHelpText>
        <label>Group Designation</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is for the portal site.  It directs the portal on how to use the URLs present in the object.</description>
        <label>Home Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Migrated__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Migrated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <description>Queue Name</description>
        <label>Queue Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requires_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Short_description__c</fullName>
        <label>Short description</label>
        <length>700</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>System_Application__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This describes if the application is a system application vs a business application.  It usually provisions base-level access.</description>
        <label>System Application</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Entitlements__c.object
<CustomObject>
    <fields>
        <fullName>AD_Group_Optional__c</fullName>
        <label>AD Group Optional</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AD_Group__c</fullName>
        <label>AD Group Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Ent_Code__c</fullName>
        <label>Entitlement Code</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentApp__c</fullName>
        <label>ParentApp</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Available Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requires_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires Approval</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Corporate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Corporate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FGI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FGI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>JobClassification__c</fullName>
        <label>Job Function</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ag Member</fullName>
                </value>
                <value>
                    <fullName>Broker - Foodservice</fullName>
                </value>
                <value>
                    <fullName>Broker - Retail</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Member</fullName>
                </value>
                <value>
                    <fullName>Dairy Member Owner</fullName>
                </value>
                <value>
                    <fullName>Direct Ag Producer</fullName>
                </value>
                <value>
                    <fullName>Farmer</fullName>
                </value>
                <value>
                    <fullName>Member of a Member</fullName>
                </value>
                <value>
                    <fullName>Member Owner</fullName>
                </value>
                <value>
                    <fullName>Momentum Consultant</fullName>
                </value>
                <value>
                    <fullName>Nutritionist</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Retailer Management</fullName>
                </value>
                <value>
                    <fullName>Retailer Operations</fullName>
                </value>
                <value>
                    <fullName>Retailer Sales</fullName>
                </value>
                <value>
                    <fullName>RTech Partner</fullName>
                </value>
                <value>
                    <fullName>Warehousing Partner</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>lol__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dairy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>purina__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Purina</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>seed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>WinField</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UserProvisioningRequest.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>User Provisioning Requests</relationshipLabel>
        <relationshipName>User_Provisioning_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EMSHomeCntrl.cls
public without sharing class EMSHomeCntrl{
    
    public AccessPageWrapper APWrapper{get;set;}
    private String userId{get;set;}
    public User userDB {get;set;}
    
    class AccessPageWrapper{
        public Integer pendingSize {get;set;}
        public Integer grantedSize {get;set;}
        public Integer availableSize {get;set;}
        public Map<String, List<Application__c>> pendingAppMap{get;set;}
        public Map<String, List<Application__c>> grantedMap{get;set;}
        public Map<String, List<CatalogWrapper>> avalAppMap{get;set;}
        
        public AccessPageWrapper(Integer pendingSize, Integer grantedSize, Integer availableSize, Map<String, List<Application__c>> pendingAppMap,
                                 Map<String, List<Application__c>> grantedMap, Map<String, List<CatalogWrapper>> avalAppMap) {
                                     this.pendingSize = pendingSize;
                                     this.grantedSize = grantedSize;
                                     this.availableSize = availableSize;
                                     this.pendingAppMap = pendingAppMap;
                                     this.grantedMap = grantedMap;
                                     this.avalAppMap = avalAppMap;
                                 }
    }
    
    public PageReference redir() {
        String JobClassification = [Select JobClassification__c From User Where Id =: UserInfo.getUserId()][0].JobClassification__c;
        if ((JobClassification != null && JobClassification.equalsIgnoreCase('Farmer'))){
            PageReference newPage = new PageReference('/ems/EMSProfilePage');
            return newPage;
        }
        return null;
    }
    
    public EMSHomeCntrl(){
        if (UserInfo.getUserType().equalsIgnoreCase('GUEST')) {
            throw new NoAccessException();
        }
        userId = System.currentPageReference().getParameters().get('userId');
        if(userId == null || String.isBlank(userId)) {
            userId = UserInfo.getUserId();
        }
        userDB = [Select Firstname,Lastname,Corporate__c,lol__c,purina__c,seed__c,FGI__c from User Where Id=:userId LIMIT 1];
        try {
            //pending apps 
            List<Id> pendingConnectedAppIds = new List<Id>();
            for (UserProvisioningRequest urp: [SELECT ConnectedAppId FROM UserProvisioningRequest WHERE 
                                               SalesforceUserId=:userId and State != 'Completed' and State != 'Failed'])
            {
                pendingConnectedAppIds.add(urp.ConnectedAppId);
            }
            List<Application__c> pendingApps = [SELECT Name,Description__c,Short_description__c,Children_allowed__c,Business__c,FG_Instructions__c,FG_Max_Ents__c,FG_mgmt__c from Application__c where isDeleted = false 
                                                and Business__c != null and System_Application__c=false and Connected_App_Id__c IN :pendingConnectedAppIds];
            Map<String, List<Application__c>> pendingAppMap = new Map<String, List<Application__c>>();
            if(pendingApps != null && pendingApps.size() > 0) {
                List<Application__c> tempList3 = new List<Application__c>();
                for(Application__c app : pendingApps) {
                    if(app.Business__c.contains(';')) {
                        tempList3.add(app);
                    } else {
                        List<Application__c> tempList;
                        if (!pendingAppMap.containsKey(app.Business__c)){
                            tempList = new List<Application__c>();
                            tempList.add(app);
                            pendingAppMap.put(app.Business__c, tempList);
                        } else {
                            tempList = pendingAppMap.get(app.Business__c);
                            tempList.add(app);
                            pendingAppMap.put(app.Business__c, tempList);
                        }
                    }
                }
                if(!tempList3.isEmpty()) {
                    pendingAppMap.put('Multiple Business Units', tempList3);   
                }
            }
            //granted apps 
            List<Id> grantedConnectedAppIds = new List<Id>();
            for (UserProvAccount upa : [SELECT ConnectedAppId FROM UserProvAccount WHERE SalesforceUserId = :userId AND Status != 'Deactivated']){
                grantedConnectedAppIds.add(upa.ConnectedAppId);
            }
            List<Application__c> grantedApps = [SELECT Name,Home_Page__c,Description__c,Short_description__c,Business__c,FG_Instructions__c,FG_Max_Ents__c,FG_mgmt__c from Application__c where isDeleted = false 
                                                and Business__c != null and System_Application__c=false and Connected_App_Id__c IN :grantedConnectedAppIds];
            Map<String, List<Application__c>> grantedAppMap = new Map<String, List<Application__c>>();
            Map<String, Boolean> businnesUnitHomePage = new Map<String, Boolean>();
            if(grantedApps != null && grantedApps.size() > 0) {
                List<Application__c> tempList2 = new List<Application__c>();
                for(Application__c app : grantedApps) {
                    if(app.Home_Page__c) {
                        businnesUnitHomePage.put(app.Business__c, app.Home_Page__c);
                    }
                    if(app.Business__c.contains(';')) {
                        tempList2.add(app);
                    } else {
                        List<Application__c> tempList;
                        if (!grantedAppMap.containsKey(app.Business__c)){
                            tempList = new List<Application__c>();
                            tempList.add(app);
                            grantedAppMap.put(app.Business__c, tempList);
                        } else {
                            tempList = grantedAppMap.get(app.Business__c);
                            tempList.add(app);
                            grantedAppMap.put(app.Business__c, tempList);
                        }
                    }
                }
                if(!tempList2.isEmpty()) {
                    grantedAppMap.put('Multiple Business Units', tempList2);   
                }
            }
            
            //available apps 
            List<Id> availableConnectedAppIds = new List<Id>();
            availableConnectedAppIds.addAll(pendingConnectedAppIds);
            availableConnectedAppIds.addAll(grantedConnectedAppIds);
            List<Application__c> availableApps = [SELECT Name,ApproverType__c,Children_allowed__c,Short_description__c,Queue_Name__c,Approver__c,Group_Designation__c,Home_Page__c,App_Code__c,Description__c,Business__c,
                                                  Migrated__c,Connected_App_ID__c,Requires_Approval__c,FG_Instructions__c,FG_Max_Ents__c,FG_mgmt__c,
                                                  (SELECT AD_Group_Optional__c,AD_Group__c,Ent_Code__c,Id,Name FROM Entitlements__r)
                                                  from Application__c where isDeleted = false AND Visible__c = true
                                                  AND Business__c != null AND System_Application__c=false AND Connected_App_Id__c NOT IN :availableConnectedAppIds];
            Map<String, List<CatalogWrapper>> avalAppMap = new Map<String, List<CatalogWrapper>>();
            if(availableApps != null && availableApps.size() > 0) {
                List<CatalogWrapper> tempList1 = new List<CatalogWrapper>();
                List<CatalogWrapper> businessLinks = new List<CatalogWrapper>();
                for(Application__c app : availableApps) {
                    List<Entitlements__c> availableEnts =  app.Entitlements__r;
                    CatalogWrapper cw = new CatalogWrapper(app, availableEnts);
                    if(app.Business__c.contains(';') && isMultiAppShow(businnesUnitHomePage, app.Business__c)  
                        /*&& (businnesUnitHomePage.get(app.Business__c) != null && businnesUnitHomePage.get(app.Business__c))*/) {
                           tempList1.add(cw);
                       } else if(app.Home_Page__c) {
                           businessLinks.add(cw);
                       } else if ((businnesUnitHomePage.get(app.Business__c) != null && businnesUnitHomePage.get(app.Business__c))){
                           List<CatalogWrapper> tempList;
                           if (!avalAppMap.containsKey(app.Business__c)){
                               tempList = new List<CatalogWrapper>();
                               tempList.add(cw);
                               avalAppMap.put(app.Business__c, tempList);
                           } else {
                               tempList = avalAppMap.get(app.Business__c);
                               tempList.add(cw);
                               avalAppMap.put(app.Business__c, tempList);
                           }
                       }
                }
                if(!tempList1.isEmpty()) {
                    avalAppMap.put('Multiple Business Units', tempList1);   
                }
                if(!businessLinks.isEmpty()) {
                    avalAppMap.put('Business Link Home Pages', businessLinks);   
                }
            }
            Integer size = 0;
            for (List<CatalogWrapper> lists : avalAppMap.values())
                size += lists.size();
            APWrapper = new AccessPageWrapper(pendingApps.size(),grantedApps.size(), size, 
                                              pendingAppMap, grantedAppMap, avalAppMap);
        } catch(Exception e){
            System.debug('##############Exception################ => ' + e);
            System.debug('##############Exception################ => ' + e.getLineNumber());
            PageMessages.addMessage(new PageMessages.PageMessage(PageMessages.Severity.ERROR, 'There was a problem initializing the page.'));
        }
    }
    
    public PageReference requestAccess(){
        List<CatalogWrapper> listTobeSend = new List<CatalogWrapper>();
        for(List<CatalogWrapper> cww : APWrapper.avalAppMap.values()) {
            for(CatalogWrapper cw : cww) {
                if(cw.checked) {
                    listTobeSend.add(cw);
                }
            }
        }
        if(!Test.isRunningTest())
        	System.enqueueJob(new EMSRequestQueuable(listTobeSend, userId));
        
        PageMessages.addMessage(new PageMessages.PageMessage(PageMessages.Severity.CONFIRM, 'Your requests have been submitted.  You will receive an email when they have been completed.'));
        return null;
    }
    
    private boolean isMultiAppShow(Map<String, Boolean> businnesUnitHomePage, String businessUnit) {
        boolean flag = false;
        for(String str : businessUnit.split('\\;')) {
            if(businnesUnitHomePage.containsKey(str) && businnesUnitHomePage.get(str)) {
                flag = true;
                break;
            }
        }
        
        return flag;
    }
}