objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Connected_App_ID__c</fullName>
        <label>Connected App ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EMS_Application_Object_Name__c</fullName>
        <description>This is the name of the profile, permission set, or custom permission that should be added to the user</description>
        <inlineHelpText>This is the name of the profile, permission set, or custom permission that should be added to the user</inlineHelpText>
        <label>EMS Application Object Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EMS_Application_Type__c</fullName>
        <label>EMS Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Custom Permission</fullName>
                </value>
                <value>
                    <fullName>Permission Set</fullName>
                </value>
                <value>
                    <fullName>Profile</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EMS_Application__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EMS Application</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Cart_Application__c.object
<CustomObject>
    <fields>
        <fullName>Catalog_App__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Related Requests</relationshipLabel>
        <relationshipName>Cart_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UPR_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UPR Number</label>
        <referenceTo>UserProvisioningRequest</referenceTo>
        <relationshipLabel>Cart Applications</relationshipLabel>
        <relationshipName>Cart_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Cart_Entitlement__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entilements In Car</relationshipLabel>
        <relationshipName>Requested_FG_Ents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ent_code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entitlement Code</label>
        <referenceTo>Entitlements__c</referenceTo>
        <relationshipName>Entilements_In_Car</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_App__c</fullName>
        <label>Parent App</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cart_Application__c.UPR_Number__c</field>
                <operation>equals</operation>
                <valueField>$Source.RelatedUPR__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cart_Application__c</referenceTo>
        <relationshipLabel>Cart Entitlements</relationshipLabel>
        <relationshipName>Cart_Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Cart Entitlement</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Entitlement In Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entilements In Car</pluralLabel>
    <recordTypes>
        <fullName>Role</fullName>
        <active>true</active>
        <label>Role</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entitlements__c.object
<CustomObject>
    <fields>
        <fullName>Ent_Code__c</fullName>
        <label>Entitlement Code</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentApp__c</fullName>
        <label>ParentApp</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Available Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

objects/UserProvFineEntitlement__c.object
<CustomObject>
    <fields>
        <fullName>Entitled_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Entitled Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Provisioned_Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentApp__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>UP Fine Grain Entitlements</relationshipLabel>
        <relationshipName>Fine_Grained_Entitlements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_SF_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related SF User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Fine_Grained_Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UPA_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related UPA</label>
        <referenceTo>UserProvAccount</referenceTo>
        <relationshipLabel>UP Fine Grain Entitlements</relationshipLabel>
        <relationshipName>Fine_Grained_Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/UserProvisionEntitlement__c.object
<CustomObject>
    <fields>
        <fullName>Entitlement_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entitlement Code</label>
        <referenceTo>Entitlements__c</referenceTo>
        <relationshipLabel>User Provision Entitlements</relationshipLabel>
        <relationshipName>CatalogEnt</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentApp__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>User Provision Entitlements</relationshipLabel>
        <relationshipName>ProvEnts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_SF_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related SF User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Provision_Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UPA_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Provisioning Account</label>
        <referenceTo>UserProvAccount</referenceTo>
        <relationshipLabel>User Provision Entitlements</relationshipLabel>
        <relationshipName>User_Provision_Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Provision Entitlement</label>
    <nameField>
        <displayFormat>UPE-{00000000}</displayFormat>
        <label>UserProvisionEntitlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Provision Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UserProvisioningRequest.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>SalesforceUser.Contact.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>User Provisioning Requests</relationshipLabel>
        <relationshipName>User_Provisioning_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EMSProvExtendObjectUtils.cls
public class EMSProvExtendObjectUtils implements Queueable{

    private static String BASIC_PROFILE = 'EMS External User';
    private UserProvAccount upa;
   List<Cart_Entitlement__c> cartEnts;
   Id targetAppId;
   String operation;
    

    public EMSProvExtendObjectUtils(UserProvAccount upaIn){
        upa = upaIn;
        operation='Create';
        targetAppId = [SELECT Id from Application__c where Connected_App_Id__c = :upaIn.ConnectedAppId LIMIT 1].ID;

    }

   public EMSProvExtendObjectUtils(UserProvAccount upaIn, List<Cart_Entitlement__c> ents,Id targetApp){
      upa = upaIn;
      cartEnts = ents;
      targetAppId = targetApp;
      operation='Create';
   }

 public EMSProvExtendObjectUtils(UserProvAccount upaIn, List<Cart_Entitlement__c> ents,Id targetApp,String operationIn){
      upa = upaIn;
      cartEnts = ents;
      targetAppId = targetApp;
      operation=operationIn;

   }

    public void execute(QueueableContext context){
        
        if (operation.equals('Create')){
    
            if (cartEnts == null){
                List<Cart_Application__c> cartApps = [Select Name, Catalog_App__c, (SELECT Id, Ent_Code__c,ent_code__r.ParentApp__c,RecordType.DeveloperName from Cart_Entitlements__r) from Cart_Application__c where upr_number__c in (select Id from UserProvisioningRequest where UserProvAccountId=:upa.Id)];
                if (cartApps != null && cartApps.size()>0){
                    Cart_Application__c cartApp = cartApps[0];
                    targetAppId = cartApp.Catalog_App__c;
                
            
                    cartEnts = cartApp.Cart_Entitlements__r;
                }
            }

            if (cartEnts != null){
                for (Cart_Entitlement__c cartEnt : cartEnts){
                    if (cartEnt.RecordType.DeveloperName == 'Role'){
                        if (doesUPEExist(upa.Id, cartEnt.ent_code__c)==false){
                            UserProvisionEntitlement__c upe = new UserProvisionEntitlement__c();
                            upe.Entitlement_Code__c = cartEnt.ent_code__c;
                            upe.UPA_Parent__c = upa.Id;
                            upe.ParentApp__c = targetAppId;
                            upe.Related_SF_User__C = upa.SalesforceUserId;
                            System.debug('UPE:'+ upe);
                            insert upe;
                        }
                    }
                    else{
                        if (doesUPFEExist(upa.Id, cartEnt.account__c)==false){
                            UserProvFineEntitlement__c upe = new UserProvFineEntitlement__c();
                            upe.Entitled_Account__c = cartEnt.account__c;
                            upe.UPA_Parent__c = upa.Id;
                            upe.ParentApp__c = targetAppId;
                            upe.Related_SF_User__C = upa.SalesforceUserId;
                            System.debug('UPFE:'+ upe);
                            insert upe;
                        }
                    }
                    
                }
            }

            Application__c targetApp = [SELECT EMS_Application__c, EMS_Application_Object_Name__c, EMS_Application_Type__c from Application__c where Id=:targetappId];
            

            System.debug('EMS App:' + targetApp.EMS_Application__c + ', Type:'+targetApp.EMS_Application_Type__c +'Object Name'+ targetApp.EMS_Application_Object_Name__c);
 
             if (targetApp.EMS_Application__c == true){
                    if (targetApp.EMS_Application_Type__c == 'Profile' && !String.isBlank(targetApp.EMS_Application_Object_Name__c)){
                       
                       Profile prof = [SELECT Id,Name FROM Profile WHERE Name=:targetApp.EMS_Application_Object_Name__c LIMIT 1 ];
                      Id userJobId = System.enqueueJob(new UpdateUserQueueable(upa.SalesforceUserId,'ProfileId',prof.Id));
                    
                        
                    }


                }
        }
        else if (operation.equalsIgnoreCase('Deactivate')){
            UserProvisionEntitlement__c[] upes = [SELECT Id,Entitlement_Code__c from UserProvisionEntitlement__c where UPA_parent__c=:upa.Id];
            for(UserProvisionEntitlement__c upe: upes){
                delete upe;
            }
            UserProvFineEntitlement__c[] upfes = [SELECT Id from UserProvFineEntitlement__c where UPA_parent__c=:upa.Id];
            for(UserProvFineEntitlement__c upfe: upfes){
                delete upfe;
            }

            UserProvAccount upa1 = [SELEcT Id,Status from UserProvAccount where id=:upa.Id limit 1];
            if (upa1.status == 'Active')
            {
                upa1.status = 'Deactivated';
                update upa1;
            }   
            Application__c targetApp = [SELECT EMS_Application__c, EMS_Application_Object_Name__c, EMS_Application_Type__c from Application__c where Id=:targetappId];
    

            if (targetApp.EMS_Application__c == true){
                    if (targetApp.EMS_Application_Type__c == 'Profile' ){
                       
                       Profile prof = [SELECT Id,Name FROM Profile WHERE Name=:BASIC_PROFILE LIMIT 1 ];
                      Id userJobId = System.enqueueJob(new UpdateUserQueueable(upa.SalesforceUserId,'ProfileId',prof.Id));
                        
                    }
                    

                }

        }
        else if (operation.equalsIgnoreCase(EMSConstants.UPDATE_OPERATION)){
            System.debug('need to add in UPEs');
            UserProvisionEntitlement__c[] upes = [SELECT Entitlement_Code__c from UserProvisionEntitlement__c where UPA_parent__c=:upa.Id];
            Set<String> provEnts = new Set<String>();
            Set<String> newEnts = new Set<String>();
            for(UserProvisionEntitlement__c upe: upes){
                provEnts.add(upe.Entitlement_Code__c);
            }

            UserProvFineEntitlement__c[] upfes = [SELECT Entitled_Account__c from UserProvFineEntitlement__c where UPA_parent__c=:upa.Id];
            Set<String> provFEnts = new Set<String>();
            Set<String> newFEnts = new Set<String>();
            for(UserProvFineEntitlement__c upfe: upfes){
                provFEnts.add(upfe.Entitled_Account__c);
            }
 
            if (cartEnts != null){
                for (Cart_Entitlement__c cartEnt : cartEnts){
                    if (cartEnt.RecordType.DeveloperName == 'Role'){
                        newEnts.add(cartEnt.ent_code__c);
                        if (!provEnts.contains(cartEnt.ent_code__c)){
                            UserProvisionEntitlement__c upe = new UserProvisionEntitlement__c();
                            upe.Entitlement_Code__c = cartEnt.ent_code__c;
                            upe.UPA_Parent__c = upa.Id;
                            upe.ParentApp__c = targetAppId;
                            upe.Related_SF_User__C = upa.SalesforceUserId;
                            System.debug('UPE:'+ upe);
                            insert upe;
                            
                        }
                    }
                    else{
                        newFEnts.add(cartEnt.Account__c);
                        
                        if (!provFEnts.contains(cartEnt.account__c)){
                            UserProvFineEntitlement__c upfe = new UserProvFineEntitlement__c();
                            upfe.Entitled_Account__c = cartEnt.Account__c;
                            upfe.UPA_Parent__c = upa.Id;
                            upfe.ParentApp__c = targetAppId;
                            upfe.Related_SF_User__C = upa.SalesforceUserId;
                            System.debug('UPFE:'+ upfe);
                            insert upfe;
                            
                        }
                    }
                    
                }

            }
            //now we need to delete what we shouldn't keep.
            for(UserProvisionEntitlement__c upe: upes){
                if (!newEnts.contains(upe.Entitlement_Code__c)){
                    delete upe;
                }
            }
            //now we need to delete what we shouldn't keep.
            for(UserProvFineEntitlement__c upfe: upfes){
                if (!newFEnts.contains(upfe.Entitled_Account__c)){
                    delete upfe;
                }
            }


        }


    }

    public boolean doesUPEExist(Id upaId, Id ent_code){


        UserProvisionEntitlement__c[] upes = [SELECT Entitlement_Code__c from UserProvisionEntitlement__c where UPA_parent__c=:upaId and Entitlement_Code__c=:ent_code];
        if (upes.size() > 0) return true;
        else return false;


    }
    public boolean doesUPFEExist(Id upaId, Id accountId){


        UserProvFineEntitlement__c[] upes = [SELECT Entitled_Account__c from UserProvFineEntitlement__c where UPA_Parent__c=:upaId and Entitled_Account__c=:accountId];
        if (upes.size() > 0) return true;
        else return false;


    }
}