objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>App_Code__c</fullName>
        <externalId>true</externalId>
        <label>App Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Group_Designation__c</fullName>
        <inlineHelpText>This is the text for a potential group representation, like the AD group.</inlineHelpText>
        <label>Group Designation</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Page__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is for the portal site.  It directs the portal on how to use the URLs present in the object.</description>
        <label>Home Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Migrated__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Migrated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_AD_Role_Name__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Roles Use AD Role Name Attribute</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <externalId>true</externalId>
        <label>BusinessLink ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Related_External_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related External User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entitlements__c.object
<CustomObject>
    <fields>
        <fullName>AD_Group_Optional__c</fullName>
        <label>AD Group Optional</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AD_Group__c</fullName>
        <label>AD Group Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ent_Code__c</fullName>
        <label>Entitlement Code</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentApp__c</fullName>
        <label>ParentApp</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Available Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <externalId>true</externalId>
        <label>BusinessLink ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>BYOID__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Login name is email address</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UserProvisionEntitlement__c.object
<CustomObject>
    <fields>
        <fullName>Entitlement_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entitlement Code</label>
        <referenceTo>Entitlements__c</referenceTo>
        <relationshipLabel>User Provision Entitlements</relationshipLabel>
        <relationshipName>CatalogEnt</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentApp__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>User Provision Entitlements</relationshipLabel>
        <relationshipName>ProvEnts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_SF_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related SF User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Provision_Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UPA_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Provisioning Account</label>
        <referenceTo>UserProvAccount</referenceTo>
        <relationshipLabel>User Provision Entitlements</relationshipLabel>
        <relationshipName>User_Provision_Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Provision Entitlement</label>
    <nameField>
        <displayFormat>UPE-{00000000}</displayFormat>
        <label>UserProvisionEntitlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Provision Entitlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UserProvisioningServiceTest.cls
@isTest(SeeAllData=true)
private class UserProvisioningServiceTest {
    
    static testMethod void testCreateUser() {
        
        Test.setMock(HttpCalloutMock.class, new UserProvisioningServiceTest.MockHttpResponseGenerator());
        
        
        UserProvisioningService svc = new UserProvisioningService();
        String firstName = 'Alex';
        String lastName = 'Smith';
        String email = EMSUtils.generateRandomString(10) + '@identigral.com';
        String company = 'Identigral';
        String division = 'Winfield';
        String password = 'Welcome1!';
        String phone = '111-222-2222';
        String state = 'MN';
        String aimsNumber = '123566';
        try {
            String ag2agID = svc.createUser(password,firstName,lastName,email,phone,company,division,'Broker',aimsNumber,state);
            //(String password,String firstName, String lastName, String email,String phone, String company,String division,String userType) {
        }
        catch (Exception e) {
            //System.assert(false,'Failed to generate Ag2Ag ID : ' + e.getMessage());
        }
    }
    
    @isTest static void testImportCSVNewError3() {
        Test.setMock(HttpCalloutMock.class, new UserProvisioningServiceTest.MockHttpResponseGenerator());
        UserProvisionEntitlement__c UPE = [Select Entitlement_Code__r.Ent_Code__c,Entitlement_Code__r.Id,Entitlement_Code__r.AD_Group__c,Entitlement_Code__r.Ad_Group_Optional__c,
                                           Entitlement_Code__r.Name,Related_SF_User__r.Id,Related_SF_User__r.Contact.ID,
                                           ParentApp__r.App_Code__c,ParentApp__r.Use_AD_Role_Name__c,ParentApp__r.Id,ParentApp__r.Group_Designation__c,ParentApp__r.Home_Page__c,ParentApp__r.Migrated__c,
                                           Related_SF_User__r.Ag2Ag_ID__c,Related_SF_User__r.Username,Related_SF_User__r.Email,UPA_Parent__r.ConnectedApp.Id
                                           from UserProvisionEntitlement__c LIMIT 1];
        String conId = UPE.Related_SF_User__r.Contact.ID;
        UserProvisioningService svc = new UserProvisioningService();
        svc.entitleUser(UPE.Related_SF_User__r, UPE.ParentApp__r, new Set<Entitlements__c>{UPE.Entitlement_Code__r}, 'reason');
        svc.entitleUser(UPE.Related_SF_User__r, UPE.ParentApp__r, new Set<Entitlements__c>{UPE.Entitlement_Code__r});
        svc.modifyUserEntitlementsByAction(UPE.Related_SF_User__r, UPE.ParentApp__r, new Set<Entitlements__c>{UPE.Entitlement_Code__r}, 'reason','action');
        svc.modifyUserAccess(UPE.Related_SF_User__r, UPE.ParentApp__r, new Set<Entitlements__c>{UPE.Entitlement_Code__r}, 'reason');
        svc.disableUserAccess(UPE.Related_SF_User__r, UPE.ParentApp__r, new Set<Entitlements__c>{UPE.Entitlement_Code__r}, 'reason');
        svc.changePassword(UPE.Related_SF_User__r, 'changePassword');
        Contact con = [Select Related_External_User__r.BYOID__c,Lastname,FirstName,Email,Phone from Contact where Id=: conId];
        svc.changeContact(UPE.Related_SF_User__r.Ag2Ag_ID__c, con);
        svc.findUser(UPE.Related_SF_User__r.Email);
        svc.disableUser(UPE.Related_SF_User__r);
        UserHelper.updateUserEmailVerification(UPE.Related_SF_User__r.Username, true);
    }
    
    class MockHttpResponseGenerator implements HttpCalloutMock {
        
        public HTTPResponse respond(HTTPRequest req) {
            // Optionally, only send a mock response for a specific endpoint and method.
            // System.assertEquals('http://api.salesforce.com/foo/bar', req.getEndpoint());
            //System.assertEquals('POST', req.getMethod());
            
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"foo":"bar"}');
            res.setStatusCode(200);
            return res;
        }
    }
}