objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requires_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires Approval</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Cart_Application__c.object
<CustomObject>
    <fields>
        <fullName>Catalog_App__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Related Requests</relationshipLabel>
        <relationshipName>Cart_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UPR_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UPR Number</label>
        <referenceTo>UserProvisioningRequest</referenceTo>
        <relationshipLabel>Cart Applications</relationshipLabel>
        <relationshipName>Cart_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Cart_Entitlement__c.object
<CustomObject>
    <fields>
        <fullName>Ent_code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entitlement Code</label>
        <referenceTo>Entitlements__c</referenceTo>
        <relationshipName>Entilements_In_Car</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_App__c</fullName>
        <label>Parent App</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cart_Application__c.UPR_Number__c</field>
                <operation>equals</operation>
                <valueField>$Source.RelatedUPR__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cart_Application__c</referenceTo>
        <relationshipLabel>Cart Entitlements</relationshipLabel>
        <relationshipName>Cart_Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RelatedUPR__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>User Provisioning Request</label>
        <referenceTo>UserProvisioningRequest</referenceTo>
        <relationshipLabel>Requested Entitlements</relationshipLabel>
        <relationshipName>uprentitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cart Entitlement</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Entitlement In Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entilements In Car</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Entitlements__c.object
<CustomObject>
    <fields>
        <fullName>AD_Group_Optional__c</fullName>
        <label>AD Group Optional</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AD_Group__c</fullName>
        <label>AD Group Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ent_Code__c</fullName>
        <label>Entitlement Code</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentApp__c</fullName>
        <label>ParentApp</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Available Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requires_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires Approval</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <externalId>true</externalId>
        <label>BusinessLink ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>External_Fed_Id__c</fullName>
        <externalId>true</externalId>
        <label>Portal Login</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/UserProvisioningRequest.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <formula>SalesforceUser.Ag2Ag_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BusinessLink ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>User Provisioning Requests</relationshipLabel>
        <relationshipName>User_Provisioning_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Reason__c</fullName>
        <label>User Reason</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EMSRequestModificationPopup.cls
public without sharing class EMSRequestModificationPopup {

	public SelectOption[] selectedEntitlements { get; set; }
    public SelectOption[] allEntitlements { get; set; }
    private String userId;
	private Id applicationId;
	public User userForRequest{get;set;}
	public Application__c app{get;set;}
	public String comments{get;set;}
	ApplicationHelper ah;
	private Id uprId;
	private String mode;
	public boolean edit{get;set;}
	EMSUPRHelper uprHelper;
	public String operation{get;set;}



	public EMSRequestModificationPopup() {
		edit = false;
		userId = System.currentPageReference().getParameters().get('userId');
		applicationId = System.currentPageReference().getParameters().get('appId');
		uprId = System.currentPageReference().getParameters().get('uprId');
		mode = System.currentPageReference().getParameters().get('mode');
		if (mode.equalsIgnoreCase('edit')) edit = true;
		selectedEntitlements =  new List<SelectOption>();
		allEntitlements = new List<SelectOption>();
		//get user information
		//userForRequest = [SELECT Id, Name from User where Id=:userId LIMIT 1];
		userForRequest = [Select Id,Name,Username,External_Fed_Id__c,FirstName,LastName,Email,Ag2Ag_ID__c from User where Id = :userId LIMIT 1];
		System.debug('the user is:'+ userForRequest.Name);
		EMSUPRHelper uprHelper = new EMSUPRHelper(uprId,applicationId);
		comments = uprHelper.getUserReason();
		this.operation = uprHelper.getOperation();
		if (operation.equalsIgnoreCase('Deactivate')) edit=false;

		//get application information
		ah = new ApplicationHelper(applicationId);
		app = ah.getApplication();
		System.debug('The application name is:' + app.Name);
		List<Entitlements__c> availableEnts = [SELECT AD_Group_Optional__c,AD_Group__c,Ent_Code__c,Id,Name FROM Entitlements__c where ParentApp__c=:app.Id];
		System.debug('there are available ents:' + availableEnts.size());
		List<Entitlements__c> provEnts = new List<Entitlements__C>(uprHelper.getUPREntitlements());
		for(Entitlements__c ent:provEnts){
			selectedEntitlements.add(new SelectOption(ent.Id,ent.Name));
		}
		Set<SelectOption> sos = new Set<SelectOption>(selectedEntitlements);
		for(Entitlements__c ent:availableEnts){
			System.debug('the ent name is: '+ ent.Name);
			SelectOption so = new SelectOption(ent.Id,ent.Name);
			if (!sos.contains(so))
				allEntitlements.add(so);
		}

	
	}

	public void updateRequest(){
		List<Entitlements__c> ents2 = new List<Entitlements__c>();
		Set<Id> entIds = new Set<Id>();
		for ( SelectOption so : selectedEntitlements ) {
			entIds.add(so.getValue());
		}
		ents2 = [SELECT AD_Group_Optional__c,AD_Group__c,Approver__c,Ent_Code__c,Id,Name,ParentApp__c,Requires_Approval__c FROM Entitlements__c where Id in :entIds];
     	
		UserProvisioningRequest upr = new UserProvisioningRequest(id=uprId);
		upr.User_Reason__c = comments;
		update upr;

			//get cart app
		Cart_Application__c[] cartApps = [Select Name, Catalog_App__c, (SELECT Id, Ent_Code__c,Ent_Code__r.ParentApp__c from Cart_Entitlements__r) from Cart_Application__c where UPR_Number__c=:uprId LIMIT 1];
		if (cartApps != null && cartApps.size()>0){
			Cart_Application__c cartApp = cartApps[0];
   			
   		
   			Cart_Entitlement__c[] cartEnts = cartApp.Cart_Entitlements__r;
   			delete cartEnts;
        
            for (Entitlements__c ent : ents2){
            	
	                Cart_Entitlement__c cEnt = new Cart_Entitlement__c();
	                cEnt.Ent_code__c = ent.Id;
	                cEnt.Parent_App__c = cartApp.Id;
	                cEnt.RelatedUPR__c = uprId;
	                insert cEnt;
            }
            	
           }
        
        

     }

	public void cancel(){


	}

}