objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Manager_Email__c</fullName>
        <label>Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Manager_Name__c</fullName>
        <label>Manager Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_Phone__c</fullName>
        <label>Manager Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Registration_Denied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Registration Denied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Retailer_City__c</fullName>
        <label>Retailer City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retailer_Name__c</fullName>
        <label>Retailer Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retailer_State__c</fullName>
        <label>Retailer State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Grower__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Grower</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Initial_Password__c</fullName>
        <description>Temporary holder of the password requested by the end user.  After the User record is created, the value of this field is cleared out</description>
        <label>Initial Password</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>JobClassification__c</fullName>
        <label>Job Function</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ag Member</fullName>
                </value>
                <value>
                    <fullName>Broker - Foodservice</fullName>
                </value>
                <value>
                    <fullName>Broker - Retail</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Consultant</fullName>
                </value>
                <value>
                    <fullName>Dairy Member</fullName>
                </value>
                <value>
                    <fullName>Dairy Member Owner</fullName>
                </value>
                <value>
                    <fullName>Direct Ag Producer</fullName>
                </value>
                <value>
                    <fullName>Farmer</fullName>
                </value>
                <value>
                    <fullName>Member of a Member</fullName>
                </value>
                <value>
                    <fullName>Member Owner</fullName>
                </value>
                <value>
                    <fullName>Momentum Consultant</fullName>
                </value>
                <value>
                    <fullName>Nutritionist</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Retailer Management</fullName>
                </value>
                <value>
                    <fullName>Retailer Operations</fullName>
                </value>
                <value>
                    <fullName>Retailer Sales</fullName>
                </value>
                <value>
                    <fullName>RTech Partner</fullName>
                </value>
                <value>
                    <fullName>Warehousing Partner</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Reporting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Manager_Email__c</fullName>
        <formula>Contact.Manager_Email__c</formula>
        <label>Manager Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_Name__c</fullName>
        <formula>Contact.Manager_Name__c</formula>
        <label>Manager Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_Phone__c</fullName>
        <formula>Contact.Manager_Phone__c</formula>
        <label>Manager Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Status__c</fullName>
        <label>Registration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                    <default>true</default>
                    <label>Started</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Needs Email Verification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestDataUtil.cls
@isTest
public class TestDataUtil {
	public static User createUser(Integer i, String emailId, String userName, String accId, String profileId){
        User newUser = new User();
        String accountId = accId;
        String usernameBase = userName;
        newUser.Username = usernameBase + '@landolakes.com.ems.dev';
        newUser.Initial_password__c = 'welcome'+i;
        newUser.CommunityNickname = usernameBase;
        newUser.ProfileId = profileId;
        newUser.Email = emailId;
        newUser.Phone = '9999999999';
        newUser.FirstName = 'Test'+i;
        newUser.LastName = 'User'+i;
        newUser.JobClassification__c = 'Farmer';
        newUser.Grower__c = true;
        newUser.Registration_Status__c = 'Approved';
        
        return newUser;
    }
    
    public static Contact createContact(Integer i, String accId){
        Contact newUserContact = new Contact(
            FirstName = 'Test'+i,
            Lastname = 'User'+i,
            AccountId = accId,
            Email = 'test'+i+'@user'+i+'.com',
            Registration_Denied__c = false,
            Manager_Name__c = 'MgrName'+i,
            Manager_Email__c = 'mgr'+i+'@email.com',
            Manager_Phone__c = '88888888888',
            Retailer_Name__c = 'RetailerName'+i,
            Retailer_City__c = 'RetailerCity'+i,
            Retailer_State__c = 'RetailerState'+i
        );
        
        return newUserContact;
    }
}