objects/User.object
<CustomObject>
    <fields>
        <fullName>Ag2Ag_ID__c</fullName>
        <externalId>true</externalId>
        <label>BusinessLink ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Registration_Status__c</fullName>
        <label>Registration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                    <default>true</default>
                    <label>Started</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Needs Email Verification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ContactWebService.cls
global class ContactWebService {
    webservice static void updateContact(String conId) { 
        User usr = [SELECT Id, Ag2Ag_ID__c,Email, Registration_Status__c,IsActive,IsPortalEnabled FROM User WHERE ContactId=:conId LIMIT 1];
        if(usr != null) {
            List<UserProvAccount> finalListToBeUpdated = new List<UserProvAccount>();
            for(UserProvAccount upa : [Select SalesforceUserId,Status from UserProvAccount where SalesforceUserId =: usr.Id]) {
                if('Active'.equalsIgnoreCase(upa.Status))
                    upa.Status = 'Deactivated';
                finalListToBeUpdated.add(upa);
            }
            Database.update(finalListToBeUpdated);
            UserHelper.disableUserContact(conId);
            UserHelper.scrambleContactEmail(conId);
        }
    }
}